<?php defined( 'ABSPATH' ) || exit; ?>
<!-- wp:asphalt-proposal-manager/container {"uniqueId":"014f05e","css":".pc014f05e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:100%;}.pc014f05e__overlay{padding:36px 0px 0px 0px !important;display:flex;flex-direction:column;align-items:center;justify-content:center;}","display":"flex","flexDirection":"column","justifyContent":"center","maxWidth":{"type":"full-width","value":"100%"},"padding":{"top":"36px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc014f05e" data-block-id="014f05e"><div class="pc014f05e__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"52337d7","css":".pc52337d7{background:#ffffff;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc52337d7__overlay{padding:36px 36px 36px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc52337d7__overlay{padding:36px 36px 36px 36px !important;}}@media screen and (max-width: 767px){.pc52337d7__overlay{padding:18px 18px 18px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffffff"},"padding":{"top":"36px","right":"36px","bottom":"36px","left":"36px"},"paddingTablet":{"top":"36px","right":"36px","bottom":"36px","left":"36px"},"paddingMobile":{"top":"18px","right":"18px","bottom":"18px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc52337d7" data-block-id="52337d7"><div class="pc52337d7__overlay"><!-- wp:columns {"isStackedOnMobile":false,"className":"is-style-default"} -->
<div class="wp-block-columns is-not-stacked-on-mobile is-style-default"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":71,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/6/logo.webp') ) ?>" alt="" class="wp-image-71"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"5afeddd","css":".pc5afeddd{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:466px;}.pc5afeddd__overlay{padding:180px 5px 120px 5px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc5afeddd__overlay{padding:83px 0px 70px 0px !important;}}@media screen and (max-width: 767px){.pc5afeddd__overlay{padding:37px 0px 37px 0px !important;}}","maxWidth":{"type":"custom","value":466},"alignment":"left","padding":{"top":"180px","right":"5px","bottom":"120px","left":"5px"},"paddingTablet":{"top":"83px","right":"0px","bottom":"70px","left":"0px"},"paddingMobile":{"top":"37px","right":"0px","bottom":"37px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc5afeddd" data-block-id="5afeddd"><div class="pc5afeddd__overlay"><!-- wp:asphalt-proposal-manager/proposal-title {"uniqueId":"e61b763","css":".pce61b763{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pce61b763__overlay{padding:0px 0px 0px 0px !important;}.pce61b763 .pc-proposal-title{text-align:left;color:#000000;font-size:64px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pce61b763{margin:0px 0px 10px 0px !important;}.pce61b763 .pc-proposal-title{font-size:48px;}}@media screen and (max-width: 767px){.pce61b763{margin:0px 0px 10px 0px !important;}}","content":"BasicProposal","fontSize":64,"fontSizeTablet":48,"fontWeight":"500","fontFamily":"Readex Pro","marginTablet":{"top":"0px","right":"0px","bottom":"10px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"10px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"2b74c14","css":".pc2b74c14{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc2b74c14__overlay{padding:0px 0px 0px 0px !important;}.pc2b74c14 .pc-client-name{text-align:left;color:#000000;font-size:18px;font-family:DM Sans;font-weight:700;}","content":"Client name","fontSize":18,"fontWeight":"700","fontFamily":"DM Sans"} /-->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"5a4fbbf","css":".pc5a4fbbf{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc5a4fbbf__overlay{padding:0px 0px 0px 0px !important;}.pc5a4fbbf .pc-sender-name{text-align:left;color:#707070;font-size:18px;font-family:DM Sans;font-weight:400;}","content":"Sender name","fontSize":18,"fontFamily":"DM Sans","color":"#707070"} /-->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"e3bff10","css":".pce3bff10{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:53px 0px 0px 0px !important;}.pce3bff10__overlay{padding:0px 0px 0px 0px !important;}.pce3bff10 .pc-heading{text-align:left;color:#000000;font-size:18px;font-family:DM Sans;font-weight:700;}","content":"Business","fontSize":18,"fontWeight":"700","fontFamily":"DM Sans","margin":{"top":"53px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pce3bff10" data-block-id="e3bff10"><div class="pce3bff10__overlay"><h2 class="pc-heading">Business</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/sender-company {"uniqueId":"dfb6984","css":".pcdfb6984{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcdfb6984__overlay{padding:0px 0px 0px 0px !important;}.pcdfb6984 .pc-sender-company{text-align:left;color:#707070;font-size:18px;font-family:DM Sans;font-weight:400;}","content":"Sender company","fontSize":18,"fontFamily":"DM Sans","color":"#707070"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cc16e00","css":".pccc16e00{background:#ffffff;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccc16e00__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccc16e00__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccc16e00__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffffff"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccc16e00" data-block-id="cc16e00"><div class="pccc16e00__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"ce4988b","css":".pcce4988b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 22px 0px !important;}.pcce4988b__overlay{padding:0px 0px 0px 0px !important;}.pcce4988b .pc-heading{text-align:left;color:#000000;font-size:48px;font-family:DM Sans;font-weight:700;}@media screen and (max-width: 1023px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:20px;}}","content":"SEO Proposal","fontSize":48,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"DM Sans","margin":{"top":"0px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcce4988b" data-block-id="ce4988b"><div class="pcce4988b__overlay"><h2 class="pc-heading">SEO Proposal</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"78a3519","css":".pc78a3519{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:1024px;}.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:flex-start;}@media screen and (max-width: 1023px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}@media screen and (max-width: 767px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}","display":"flex","displayTablet":"inline-flex","displayMobile":"inline-flex","justifyContent":"flex-start","padding":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingTablet":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"12px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc78a3519" data-block-id="78a3519"><div class="pc78a3519__overlay"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"3977628","css":".pc3977628{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 29px 0px !important;}.pc3977628__overlay{padding:0px 0px 0px 0px !important;}.pc3977628 .pc-paragraph{text-align:left;color:#707070;font-size:12px;font-family:DM Sans;font-weight:400;}","content":"To work with client to develop a full SEO identity system that represents the business and marketing materials","fontSize":12,"fontFamily":"DM Sans","color":"#707070","margin":{"top":"0px","right":"0px","bottom":"29px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc3977628" data-block-id="3977628"><div class="pc3977628__overlay"><p class="pc-paragraph">To work with client to develop a full SEO identity system that represents the business and marketing materials</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"a784274","css":".pca784274{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 8px 0px !important;}.pca784274__overlay{padding:0px 0px 0px 0px !important;}.pca784274 .pc-heading{text-align:left;color:#000000;font-size:14px;font-family:DM Sans;font-weight:700;}","content":"Project Summary","fontSize":14,"fontWeight":"700","fontFamily":"DM Sans","margin":{"top":"0px","right":"0px","bottom":"8px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pca784274" data-block-id="a784274"><div class="pca784274__overlay"><h2 class="pc-heading">Project Summary</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"1089bdc","css":".pc1089bdc{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc1089bdc__overlay{padding:0px 0px 0px 0px !important;}.pc1089bdc .pc-paragraph{text-align:left;color:#707070;font-size:12px;font-family:DM Sans;font-weight:400;}@media screen and (max-width: 1023px){.pc1089bdc .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc1089bdc .pc-paragraph{font-size:14px;}}","content":"Dear Client Name,\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eOur proposed project aims to address [briefly describe the main focus or subject of your project]. In today’s rapidly evolving landscape, this project holds significant importance due to [mention the broader context or relevance]. By tackling [the problem or challenge], we intend to [state the objectives or research questions].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eTo provide necessary context, it’s essential to understand [provide relevant background information]. [Discuss any existing challenges or gaps in the field.] Our project will operate within [describe the specific context or environment].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eAt the heart of our project lies the problem of [clearly define the issue]. Our research questions include [list the specific questions you aim to explore]. By achieving these objectives, we hope to [mention the positive impact or outcomes].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eOur proposed approach involves [briefly describe the methodology or steps you’ll take]. We plan to [outline the specific methods, tools, or techniques]. By following this approach, we aim to [mention the expected outcomes or benefits].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eOur project holds great promise for [describe the relevant stakeholders or beneficiaries]. By addressing [the problem or challenge], we anticipate [mention the positive impact or outcomes]. This project aligns with [any relevant initiatives or goals] and contributes to [broader societal or organizational objectives].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eDesignation\u003cbr\u003eJohn Doe","fontSize":12,"fontSizeTablet":14,"fontSizeMobile":14,"fontFamily":"DM Sans","color":"#707070"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc1089bdc" data-block-id="1089bdc"><div class="pc1089bdc__overlay"><p class="pc-paragraph">Dear Client Name,<br><br><br>Our proposed project aims to address [briefly describe the main focus or subject of your project]. In today’s rapidly evolving landscape, this project holds significant importance due to [mention the broader context or relevance]. By tackling [the problem or challenge], we intend to [state the objectives or research questions].<br><br><br>To provide necessary context, it’s essential to understand [provide relevant background information]. [Discuss any existing challenges or gaps in the field.] Our project will operate within [describe the specific context or environment].<br><br><br>At the heart of our project lies the problem of [clearly define the issue]. Our research questions include [list the specific questions you aim to explore]. By achieving these objectives, we hope to [mention the positive impact or outcomes].<br><br><br>Our proposed approach involves [briefly describe the methodology or steps you’ll take]. We plan to [outline the specific methods, tools, or techniques]. By following this approach, we aim to [mention the expected outcomes or benefits].<br><br><br>Our project holds great promise for [describe the relevant stakeholders or beneficiaries]. By addressing [the problem or challenge], we anticipate [mention the positive impact or outcomes]. This project aligns with [any relevant initiatives or goals] and contributes to [broader societal or organizational objectives].<br><br><br>Designation<br>John Doe</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cdd0ef3","css":".pccdd0ef3{background:#ffffff;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccdd0ef3__overlay{padding:100px 36px 300px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccdd0ef3__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccdd0ef3__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffffff"},"padding":{"top":"100px","right":"36px","bottom":"300px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccdd0ef3" data-block-id="cdd0ef3"><div class="pccdd0ef3__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"f0cbff9","css":".pcf0cbff9{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 22px 0px !important;}.pcf0cbff9__overlay{padding:0px 0px 0px 0px !important;}.pcf0cbff9 .pc-heading{text-align:left;color:#000000;font-size:48px;font-family:DM Sans;font-weight:700;}@media screen and (max-width: 1023px){.pcf0cbff9__overlay{padding:0px 0px 0px 0px !important;}.pcf0cbff9{margin:0 0 20px 0 !important;}.pcf0cbff9 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcf0cbff9{margin:0 0 20px 0 !important;}.pcf0cbff9 .pc-heading{font-size:20px;}}","content":"Objective","fontSize":48,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"DM Sans","paddingTablet":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"bottom":"20px"},"marginMobile":{"bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcf0cbff9" data-block-id="f0cbff9"><div class="pcf0cbff9__overlay"><h2 class="pc-heading">Objective</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"6258c03","css":".pc6258c03{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 29px 0px !important;}.pc6258c03__overlay{padding:0px 0px 0px 0px !important;}.pc6258c03 .pc-paragraph{text-align:left;color:#707070;font-size:12px;font-family:DM Sans;font-weight:400;}","content":"To work with client to develop a full brand identity system that represents the business and marketing materials","fontSize":12,"fontFamily":"DM Sans","color":"#707070","margin":{"top":"0px","right":"0px","bottom":"29px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc6258c03" data-block-id="6258c03"><div class="pc6258c03__overlay"><p class="pc-paragraph">To work with client to develop a full brand identity system that represents the business and marketing materials</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"c8f28ea","css":".pcc8f28ea{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcc8f28ea__overlay{padding:0px 0px 0px 0px !important;}.pcc8f28ea .pc-paragraph{text-align:left;color:#707070;font-size:12px;font-family:DM Sans;font-weight:400;}@media screen and (max-width: 767px){.pcc8f28ea .pc-paragraph{font-size:14px;}}","content":"Based on the discussion we have had where you have shared your business and project specs, your goals, mission, and challenges, I have developed a vision of further work on the design that I feel will improve your marketing and identity.\u003cbr\u003e\u003cbr\u003eMy deliveries on this project are as follows:\u003cbr\u003e\u003cbr\u003eProvide project for the website page. The page is to be designed for 3 end users: admins, external buyers, and sellers.\u003cbr\u003e\u003cbr\u003eProvide project for the website page. The page is to be designed for individual sellers (see design request).\u003cbr\u003eAll projects will contain brand colors and styles, as well as the typography, icons, and logo, that you provided earlier.\u003cbr\u003eAs per the project brief and request, the design will follow a minimalistic design that will serve such functionalities as [logging in, availability to search and find content, booking a flight, choosing dates, rejecting or accepting the booking, etc.]","fontSize":12,"fontSizeMobile":14,"fontFamily":"DM Sans","color":"#707070"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcc8f28ea" data-block-id="c8f28ea"><div class="pcc8f28ea__overlay"><p class="pc-paragraph">Based on the discussion we have had where you have shared your business and project specs, your goals, mission, and challenges, I have developed a vision of further work on the design that I feel will improve your marketing and identity.<br><br>My deliveries on this project are as follows:<br><br>Provide project for the website page. The page is to be designed for 3 end users: admins, external buyers, and sellers.<br><br>Provide project for the website page. The page is to be designed for individual sellers (see design request).<br>All projects will contain brand colors and styles, as well as the typography, icons, and logo, that you provided earlier.<br>As per the project brief and request, the design will follow a minimalistic design that will serve such functionalities as [logging in, availability to search and find content, booking a flight, choosing dates, rejecting or accepting the booking, etc.]</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"9e2f7dc","css":".pc9e2f7dc{background:#ffffff;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc9e2f7dc__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc9e2f7dc__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc9e2f7dc__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffffff"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc9e2f7dc" data-block-id="9e2f7dc"><div class="pc9e2f7dc__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"db62ab8","css":".pcdb62ab8{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 24px 0px !important;}.pcdb62ab8__overlay{padding:0px 0px 0px 0px !important;}.pcdb62ab8 .pc-heading{text-align:left;color:#000000;font-size:48px;font-family:DM Sans;font-weight:700;}@media screen and (max-width: 1023px){.pcdb62ab8{margin:0px 0 22px 0 !important;}.pcdb62ab8 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcdb62ab8{margin:0px 0 20px 0 !important;}.pcdb62ab8 .pc-heading{font-size:20px;}}","content":"Cost \u0026amp; Billing","fontSize":48,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"DM Sans","margin":{"top":"0px","right":"0px","bottom":"24px","left":"0px"},"marginTablet":{"top":"0px","bottom":"22px"},"marginMobile":{"top":"0px","bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcdb62ab8" data-block-id="db62ab8"><div class="pcdb62ab8__overlay"><h2 class="pc-heading">Cost &amp; Billing</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"4824161","css":".pc4824161{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc4824161__overlay{padding:0px 0px 0px 0px !important;}.pc4824161 .pc-paragraph{text-align:left;color:#707070;font-size:12px;font-family:DM Sans;font-weight:400;}@media screen and (max-width: 767px){.pc4824161 .pc-paragraph{font-size:14px;}}","content":"If you are unhappy about the progress of the project, feel we are not finding an appropriate angle, and/or feel that you voice and input is not being acknowledged, kindly discuss this with me. I would encourage that we schedule a call rather than e-mail ; I am very easy going and even easier to talk to.","fontSize":12,"fontSizeMobile":14,"fontFamily":"DM Sans","color":"#707070"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc4824161" data-block-id="4824161"><div class="pc4824161__overlay"><p class="pc-paragraph">If you are unhappy about the progress of the project, feel we are not finding an appropriate angle, and/or feel that you voice and input is not being acknowledged, kindly discuss this with me. I would encourage that we schedule a call rather than e-mail ; I am very easy going and even easier to talk to.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"15a8344","css":".pc15a8344{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:50px 0px 0px 0px !important;max-width:1024px;}.pc15a8344__overlay{padding:0px 0px 0px 0px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"50px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc15a8344" data-block-id="15a8344"><div class="pc15a8344__overlay"><!-- wp:asphalt-proposal-manager/pricing {"uniqueId":"b86da5b","css":".pcb86da5b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcb86da5b__overlay{padding:0px 0px 0px 0px !important;}.pcb86da5b table thead th{background-color:#000000;color:#ffffff;font-weight:500;padding:8px 14px 8px 14px;font-family:Readex Pro;font-size:14px;}.pcb86da5b table tbody{background-color:#ffffff;}.pcb86da5b table tbody tr td{border-bottom-color:#E1E1E1;padding:15px 15px 15px 15px;}.pcb86da5b table tbody tr td .pc-pricing-item-title{color:#000000;font-family:Readex Pro;font-weight:400;font-size:16px;}.pcb86da5b table tbody tr td .pc-pricing-item-wrapper{margin:0px 0px 5px 0px;}.pcb86da5b table tbody tr td .pc-pricing-item-description{color:#000000;font-family:Readex Pro;font-weight:300;font-size:14px;}.pcb86da5b table tbody tr td.pc-pricing-column{color:#000000;font-family:Readex Pro;font-weight:300;font-size:16px;}.pcb86da5b table tfoot tr.pc-subtotal-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:9px 0 0 0;}.pcb86da5b table tfoot tr.pc-adjustments-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:10px 0 0 0;}.pcb86da5b table tfoot tr.pc-total-row td{font-family:Readex Pro;font-weight:400;font-size:20px;padding:10px 0 0 0;}","tableTitle":"Project Billing","items":[{"title":"Initial design","description":"Share the initial design for feedback","price":1245,"quantity":43,"isChecked":true},{"title":"Feedback loop for design","description":"Take customer feedback from initial design","price":1245,"quantity":43,"isChecked":true},{"title":"Final design","description":"Finazlied the feedback from initial design","price":1245,"quantity":43,"isChecked":false}],"showSubtotal":true,"showTotal":true,"headerFontWeight":"500","headerFontFamily":"Readex Pro","headerFontSize":14,"headerPadding":{"top":"8px","right":"14px","bottom":"8px","left":"14px"},"bodyBackground":"#ffffff","titleColor":"#000000","titleFontFamily":"Readex Pro","titleFontWeight":"400","titleFontSize":16,"descriptionColor":"#000000","descriptionFontFamily":"Readex Pro","descriptionFontWeight":"300","descriptionFontSize":14,"pricingColor":"#000000","pricingFontFamily":"Readex Pro","pricingFontWeight":"300","pricingFontSize":16,"subtotalFontFamily":"Readex Pro","subtotalFontWeight":"400","subtotalFontSize":16,"subtotalMargin":{"top":"9px"},"adjustmentsFontFamily":"Readex Pro","adjustmentsFontWeight":"400","adjustmentsFontSize":16,"adjustmentsMargin":{"top":"10px"},"totalFontFamily":"Readex Pro","totalFontWeight":"400","totalFontSize":20,"totalMargin":{"top":"10px"},"background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"2df3d4d","css":".pc2df3d4d{background:#ffffff;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc2df3d4d__overlay{padding:100px 36px 300px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc2df3d4d__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc2df3d4d__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffffff"},"padding":{"top":"100px","right":"36px","bottom":"300px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc2df3d4d" data-block-id="2df3d4d"><div class="pc2df3d4d__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"148bcab","css":".pc148bcab{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 24px 0px !important;}.pc148bcab__overlay{padding:0px 0px 0px 0px !important;}.pc148bcab .pc-heading{text-align:left;color:#000000;font-size:48px;font-family:DM Sans;font-weight:700;}@media screen and (max-width: 1023px){.pc148bcab{margin:0px 0 22px 0 !important;}.pc148bcab .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc148bcab{margin:0px 0 20px 0 !important;}.pc148bcab .pc-heading{font-size:20px;}}","content":"Accept \u0026amp; Sign","fontSize":48,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"DM Sans","margin":{"top":"0px","right":"0px","bottom":"24px","left":"0px"},"marginTablet":{"top":"0px","bottom":"22px"},"marginMobile":{"top":"0px","bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc148bcab" data-block-id="148bcab"><div class="pc148bcab__overlay"><h2 class="pc-heading">Accept &amp; Sign</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"0246001","css":".pc0246001{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc0246001__overlay{padding:0px 0px 0px 0px !important;}.pc0246001 .pc-paragraph{text-align:left;color:#707070;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc0246001 .pc-paragraph{font-size:14px;}}","content":"By signing this proposal you agree with the deliverables and terms of services. These terms are valid for only the said provision, and the remaining provisions (if there are any other) shall continue to be valid and enforceable.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","color":"#707070"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc0246001" data-block-id="0246001"><div class="pc0246001__overlay"><p class="pc-paragraph">By signing this proposal you agree with the deliverables and terms of services. These terms are valid for only the said provision, and the remaining provisions (if there are any other) shall continue to be valid and enforceable.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"89bf94c","css":".pc89bf94c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:40px 0px 0px 0px !important;max-width:1024px;}.pc89bf94c__overlay{padding:0px 0px 0px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:space-between;}","display":"flex","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"40px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc89bf94c" data-block-id="89bf94c"><div class="pc89bf94c__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"978f004","css":".pc978f004{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pc978f004__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:column;align-items:flex-end;justify-content:flex-start;}","flexDirection":"column","alignItems":"flex-end","justifyContent":"flex-start","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pc978f004" data-block-id="978f004"><div class="pc978f004__overlay"><!-- wp:asphalt-proposal-manager/signature {"uniqueId":"dce3bdf","placeholder":"Signature","css":".pcdce3bdf{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;width:200px;}.pcdce3bdf__overlay{padding:16px 10px 16px 10px !important;}.pcdce3bdf .signature-content{text-align:center;}","fontSize":14,"fontFamily":"Readex Pro","padding":{"top":"16px","right":"10px","bottom":"16px","left":"10px"},"alignment":"center"} /-->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"3b4252a","css":".pc3b4252a{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:10px 0px 0px 0px !important;}.pc3b4252a__overlay{padding:0px 0px 0px 0px !important;}.pc3b4252a .pc-sender-name{text-align:left;color:#333333;font-size:14px;font-family:Adamina;font-weight:400;}","content":"Sender name","fontSize":14,"fontFamily":"Adamina","color":"#333333","margin":{"top":"10px","right":"0px","bottom":"0px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"4637abf","css":".pc4637abf{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pc4637abf__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:column;align-items:flex-end;justify-content:flex-start;}","flexDirection":"column","alignItems":"flex-end","justifyContent":"flex-start","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pc4637abf" data-block-id="4637abf"><div class="pc4637abf__overlay"><!-- wp:asphalt-proposal-manager/signature {"uniqueId":"bcd8ed9","userType":"client","placeholder":"Signature","css":".pcbcd8ed9{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;width:200px;}.pcbcd8ed9__overlay{padding:16px 10px 16px 10px !important;}.pcbcd8ed9 .signature-content{text-align:center;}","fontSize":14,"fontFamily":"Readex Pro","padding":{"top":"16px","right":"10px","bottom":"16px","left":"10px"},"alignment":"center"} /-->

<!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"f0c5e63","css":".pcf0c5e63{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:10px 0px 0px 0px !important;}.pcf0c5e63__overlay{padding:0px 0px 0px 0px !important;}.pcf0c5e63 .pc-client-name{text-align:left;color:#333333;font-size:14px;font-family:Adamina;font-weight:400;}","content":"Client name","fontFamily":"Adamina","color":"#333333","margin":{"top":"10px","right":"0px","bottom":"0px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->