<?php defined( 'ABSPATH' ) || exit; ?>
<!-- wp:asphalt-proposal-manager/container {"uniqueId":"014f05e","css":".pc014f05e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:100%;}.pc014f05e__overlay{padding:36px 0px 0px 0px !important;display:flex;flex-direction:column;align-items:center;justify-content:center;}","display":"flex","flexDirection":"column","justifyContent":"center","maxWidth":{"type":"full-width","value":"100%"},"padding":{"top":"36px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc014f05e" data-block-id="014f05e"><div class="pc014f05e__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"52337d7","css":".pc52337d7{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-cover-bg.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc52337d7__overlay{padding:152px 36px 100px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc52337d7__overlay{padding:36px 36px 36px 36px !important;}}@media screen and (max-width: 767px){.pc52337d7__overlay{padding:18px 18px 18px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-cover-bg.webp') ) ?>"},"padding":{"top":"152px","right":"36px","bottom":"100px","left":"36px"},"paddingTablet":{"top":"36px","right":"36px","bottom":"36px","left":"36px"},"paddingMobile":{"top":"18px","right":"18px","bottom":"18px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc52337d7" data-block-id="52337d7"><div class="pc52337d7__overlay"><!-- wp:image {"id":63,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/logo.png') ) ?>" alt="" class="wp-image-63"/></figure>
<!-- /wp:image -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/proposal-title {"uniqueId":"51a89bf","css":".pc51a89bf{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 252px 0px !important;}.pc51a89bf__overlay{padding:0px 0px 0px 0px !important;}.pc51a89bf .pc-proposal-title{text-align:left;color:#000000;font-size:40px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc51a89bf{margin:0px 0px 10px 0px !important;}.pc51a89bf .pc-proposal-title{font-size:48px;}}@media screen and (max-width: 767px){.pc51a89bf{margin:0px 0px 10px 0px !important;}.pc51a89bf .pc-proposal-title{font-size:40px;}}","content":"Social Media Marketing Proposal Template","fontSize":40,"fontSizeTablet":48,"fontSizeMobile":40,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"margin":{"top":"0px","right":"0px","bottom":"252px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"10px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"10px","left":"0px"}} /--></div>
<!-- /wp:group -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"4074b8e","css":".pc4074b8e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc4074b8e__overlay{padding:0px 0px 0px 0px !important;}.pc4074b8e .pc-heading{text-align:left;color:#000000;font-size:17px;font-family:Kadwa;font-weight:700;}","content":"Created by","fontSize":17,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc4074b8e" data-block-id="4074b8e"><div class="pc4074b8e__overlay"><h2 class="pc-heading">Created by</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"b6315f5","css":".pcb6315f5{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:6px 0px 0px 0px !important;}.pcb6315f5__overlay{padding:0px 0px 0px 0px !important;}.pcb6315f5 .pc-sender-name{text-align:left;color:#000000;font-size:16px;font-family:Kadwa;font-weight:400;}","content":"Signature","fontFamily":"Kadwa","margin":{"top":"6px","right":"0px","bottom":"0px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/sender-company {"uniqueId":"c4bc981","css":".pcc4bc981{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:6px 0px 0px 0px !important;}.pcc4bc981__overlay{padding:0px 0px 0px 0px !important;}.pcc4bc981 .pc-sender-company{text-align:left;color:#000000;font-size:16px;font-family:Kadwa;font-weight:400;}","content":"Sender company","fontFamily":"Kadwa","margin":{"top":"6px","right":"0px","bottom":"0px","left":"0px"}} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"style":{"spacing":{"padding":{"right":"0px"},"blockGap":"0px"}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group" style="padding-right:0px"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"18d5861","css":".pc18d5861{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc18d5861__overlay{padding:0px 0px 0px 0px !important;}.pc18d5861 .pc-heading{text-align:left;color:#000000;font-size:17px;font-family:Kadwa;font-weight:700;}","content":"Prepared for","fontSize":17,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc18d5861" data-block-id="18d5861"><div class="pc18d5861__overlay"><h2 class="pc-heading">Prepared for</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"88b27a1","css":".pc88b27a1{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:6px 0px 0px 0px !important;}.pc88b27a1__overlay{padding:0px 0px 0px 0px !important;}.pc88b27a1 .pc-client-name{text-align:left;color:#000000;font-size:16px;font-family:Kadwa;font-weight:400;}","content":"Client Name","fontSize":16,"fontFamily":"Kadwa","margin":{"top":"6px","right":"0px","bottom":"0px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/client-company {"uniqueId":"77fffa0","css":".pc77fffa0{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:6px 0px 0px 0px !important;}.pc77fffa0__overlay{padding:0px 0px 0px 0px !important;}.pc77fffa0 .pc-client-company{text-align:left;color:#000000;font-size:16px;font-family:Kadwa;font-weight:400;}","content":"Client company","fontFamily":"Kadwa","margin":{"top":"6px","right":"0px","bottom":"0px","left":"0px"}} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cc16e00","css":".pccc16e00{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccc16e00__overlay{padding:47px 36px 122px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccc16e00__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccc16e00__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"47px","right":"36px","bottom":"122px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccc16e00" data-block-id="cc16e00"><div class="pccc16e00__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"ce4988b","css":".pcce4988b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 22px 0px !important;}.pcce4988b__overlay{padding:5px 0px 5px 0px !important;}.pcce4988b .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:20px;}}","content":"Cover Letter","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcce4988b" data-block-id="ce4988b"><div class="pcce4988b__overlay"><h2 class="pc-heading">Cover Letter</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"78a3519","css":".pc78a3519{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:1024px;}.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:flex-start;}@media screen and (max-width: 1023px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}@media screen and (max-width: 767px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}","display":"flex","displayTablet":"inline-flex","displayMobile":"inline-flex","justifyContent":"flex-start","padding":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingTablet":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"12px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc78a3519" data-block-id="78a3519"><div class="pc78a3519__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"d09585c","css":".pcd09585c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 26px 0px !important;}.pcd09585c__overlay{padding:0px 0px 0px 0px !important;}.pcd09585c .pc-heading{text-align:left;color:#000000;font-size:14px;font-family:Kadwa;font-weight:400;}","content":"Dear client,","fontSize":14,"fontWeight":"400","fontFamily":"Kadwa","margin":{"top":"0px","right":"0px","bottom":"26px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcd09585c" data-block-id="d09585c"><div class="pcd09585c__overlay"><h2 class="pc-heading">Dear client,</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"1089bdc","css":".pc1089bdc{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc1089bdc__overlay{padding:0px 0px 0px 0px !important;}.pc1089bdc .pc-paragraph{text-align:left;color:#000000;font-size:13px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc1089bdc .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc1089bdc .pc-paragraph{font-size:14px;}}","content":"As a seasoned freelance social media manager, I am excited to apply my \u003cbr\u003eexpertise to your project. With [X years/months] of experience, I’ve \u003cbr\u003esuccessfully crafted and executed social media strategies for diverse \u003cbr\u003eclients, driving engagement and brand awareness.\u003cbr\u003eWhy I’m the Right Fit:","fontSize":13,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc1089bdc" data-block-id="1089bdc"><div class="pc1089bdc__overlay"><p class="pc-paragraph">As a seasoned freelance social media manager, I am excited to apply my <br>expertise to your project. With [X years/months] of experience, I’ve <br>successfully crafted and executed social media strategies for diverse <br>clients, driving engagement and brand awareness.<br>Why I’m the Right Fit:</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"0073265","css":".pc0073265{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc0073265__overlay{padding:0px 0px 0px 0px !important;}.pc0073265 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc0073265" data-block-id="0073265"><div class="pc0073265__overlay"><ul><li>&lt;strong&gt;Adaptability:&lt;/strong&gt;&nbsp;As a freelancer, I thrive in dynamic environments. I understand the unique challenges of managing social media independently and can swiftly adjust to meet your project’s needs.</li><li>&lt;strong&gt;Results-Driven:&lt;/strong&gt;&nbsp;My track record includes increasing followers, boosting engagement, and optimizing content across platforms. I’m committed to delivering measurable outcomes.</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"beafcdf","css":".pcbeafcdf{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcbeafcdf__overlay{padding:0px 0px 0px 0px !important;}.pcbeafcdf .pc-paragraph{text-align:left;color:#000000;font-size:13px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pcbeafcdf .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pcbeafcdf .pc-paragraph{font-size:14px;}}","content":"\u003cbr\u003e\u003cbr\u003eExamples of My Work:\u003cbr\u003e","fontSize":13,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcbeafcdf" data-block-id="beafcdf"><div class="pcbeafcdf__overlay"><p class="pc-paragraph"><br><br>Examples of My Work:<br></p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"9c27bc1","css":".pc9c27bc1{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc9c27bc1__overlay{padding:0px 0px 0px 0px !important;}.pc9c27bc1 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc9c27bc1" data-block-id="9c27bc1"><div class="pc9c27bc1__overlay"><ul><li>&lt;strong&gt;Client A:&lt;/strong&gt;&nbsp;Developed a content calendar that led to a 20% increase in Instagram followers within three months.</li><li>&lt;strong&gt;Brand B:&lt;/strong&gt;&nbsp;Launched a successful Twitter campaign that generated 1,000 retweets and expanded brand reach.</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"76b473e","css":".pc76b473e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0 0px 0px 0px !important;}.pc76b473e__overlay{padding:0px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc76b473e{margin:18px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc76b473e{margin:18px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{font-size:14px;}}","content":"I’d love to discuss how I can contribute to your project. Please feel free to \u003cbr\u003ereach out via email at [Your Email Address] or phone at [Your \u003cbr\u003ePhone Number].\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eThank you for considering my application. Let’s create social media magic together!","fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"18px","right":"0px","bottom":"0px","left":"0px"},"marginMobile":{"top":"18px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc76b473e" data-block-id="76b473e"><div class="pc76b473e__overlay"><p class="pc-paragraph">I’d love to discuss how I can contribute to your project. Please feel free to <br>reach out via email at [Your Email Address] or phone at [Your <br>Phone Number].<br><br><br>Thank you for considering my application. Let’s create social media magic together!</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cdd0ef3","css":".pccdd0ef3{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccdd0ef3__overlay{padding:50px 36px 151px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccdd0ef3__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccdd0ef3__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"50px","right":"36px","bottom":"151px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccdd0ef3" data-block-id="cdd0ef3"><div class="pccdd0ef3__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"be88b09","css":".pcbe88b09{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 50px 0px !important;}.pcbe88b09__overlay{padding:5px 0px 5px 0px !important;}.pcbe88b09 .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcbe88b09{margin:0px 0px 20px 0px !important;}.pcbe88b09 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcbe88b09{margin:0px 0px 20px 0px !important;}.pcbe88b09 .pc-heading{font-size:20px;}}","content":"Executive Summary","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"50px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcbe88b09" data-block-id="be88b09"><div class="pcbe88b09__overlay"><h2 class="pc-heading">Executive Summary</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"c6959c9","css":".pcc6959c9{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 22px 0px !important;}.pcc6959c9__overlay{padding:0px 0px 0px 0px !important;}.pcc6959c9 .pc-heading{text-align:left;color:#00ab95;font-size:20px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcc6959c9{margin:30px 0 20px 0 !important;}.pcc6959c9 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcc6959c9{margin:30px 0 18px 0 !important;}.pcc6959c9 .pc-heading{font-size:20px;}}","content":"Creating Engaging Social Content","fontSize":20,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","color":"#00ab95","margin":{"top":"16px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"30px","bottom":"20px"},"marginMobile":{"top":"30px","bottom":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcc6959c9" data-block-id="c6959c9"><div class="pcc6959c9__overlay"><h2 class="pc-heading">Creating Engaging Social Content</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"c8f28ea","css":".pcc8f28ea{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 40px 0px !important;}.pcc8f28ea__overlay{padding:0px 0px 0px 0px !important;}.pcc8f28ea .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcc8f28ea .pc-paragraph{font-size:14px;}}","content":"Creating engaging content for social media involves understanding your audience's interests and preferences to craft messages that resonate\u003cbr\u003edeeply with them. Start by telling a compelling story that evokes emotion \u003cbr\u003eand fosters a sense of connection. Use high-quality visuals and videos to \u003cbr\u003ecapture attention, and pair them with concise, impactful captions that \u003cbr\u003eencourage interaction. Incorporate trending topics and hashtags \u003cbr\u003eto increase visibility and relevance..","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"40px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcc8f28ea" data-block-id="c8f28ea"><div class="pcc8f28ea__overlay"><p class="pc-paragraph">Creating engaging content for social media involves understanding your audience's interests and preferences to craft messages that resonate<br>deeply with them. Start by telling a compelling story that evokes emotion <br>and fosters a sense of connection. Use high-quality visuals and videos to <br>capture attention, and pair them with concise, impactful captions that <br>encourage interaction. Incorporate trending topics and hashtags <br>to increase visibility and relevance..</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"858db8a","css":".pc858db8a{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:24px 0px 22px 0px !important;}.pc858db8a__overlay{padding:0px 0px 0px 0px !important;}.pc858db8a .pc-heading{text-align:left;color:#00ab95;font-size:20px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc858db8a{margin:30px 0 20px 0 !important;}.pc858db8a .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc858db8a{margin:30px 0 18px 0 !important;}.pc858db8a .pc-heading{font-size:20px;}}","content":"Posting Company Related Updates","fontSize":20,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","color":"#00ab95","margin":{"top":"24px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"30px","bottom":"20px"},"marginMobile":{"top":"30px","bottom":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc858db8a" data-block-id="858db8a"><div class="pc858db8a__overlay"><h2 class="pc-heading">Posting Company Related Updates</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"f62b8a0","css":".pcf62b8a0{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 40px 0px !important;}.pcf62b8a0__overlay{padding:0px 0px 0px 0px !important;}.pcf62b8a0 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcf62b8a0 .pc-paragraph{font-size:14px;}}","content":"Posting company-related updates on social media should be both \u003cbr\u003einformative and engaging to keep your audience interested. Start by \u003cbr\u003ehighlighting key achievements, such as new product launches, awards, or milestones, using a mix of compelling visuals and succinct, engaging copy.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"40px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcf62b8a0" data-block-id="f62b8a0"><div class="pcf62b8a0__overlay"><p class="pc-paragraph">Posting company-related updates on social media should be both <br>informative and engaging to keep your audience interested. Start by <br>highlighting key achievements, such as new product launches, awards, or milestones, using a mix of compelling visuals and succinct, engaging copy.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"cda0277","css":".pccda0277{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:24px 0px 22px 0px !important;}.pccda0277__overlay{padding:0px 0px 0px 0px !important;}.pccda0277 .pc-heading{text-align:left;color:#00ab95;font-size:20px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pccda0277{margin:30px 0 20px 0 !important;}.pccda0277 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pccda0277{margin:30px 0 18px 0 !important;}.pccda0277 .pc-heading{font-size:20px;}}","content":"Promotions and social campaigns","fontSize":20,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","color":"#00ab95","margin":{"top":"24px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"30px","bottom":"20px"},"marginMobile":{"top":"30px","bottom":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pccda0277" data-block-id="cda0277"><div class="pccda0277__overlay"><h2 class="pc-heading">Promotions and social campaigns</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"55cc1e5","css":".pc55cc1e5{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc55cc1e5__overlay{padding:0px 0px 0px 0px !important;}.pc55cc1e5 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc55cc1e5 .pc-paragraph{font-size:14px;}}","content":"Promotions and social campaigns on social media should be crafted to capture attention and drive action. Start by clearly highlighting the benefits of the promotion or campaign, using eye-catching visuals and compelling headlines to draw users in. Create a sense of urgency with limited-time offers or exclusive deals to encourage immediate engagement.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc55cc1e5" data-block-id="55cc1e5"><div class="pc55cc1e5__overlay"><p class="pc-paragraph">Promotions and social campaigns on social media should be crafted to capture attention and drive action. Start by clearly highlighting the benefits of the promotion or campaign, using eye-catching visuals and compelling headlines to draw users in. Create a sense of urgency with limited-time offers or exclusive deals to encourage immediate engagement.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"28e50e7","css":".pc28e50e7{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc28e50e7__overlay{padding:50px 36px 0px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc28e50e7__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc28e50e7__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"50px","right":"36px","bottom":"0px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc28e50e7" data-block-id="28e50e7"><div class="pc28e50e7__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"5b57eea","css":".pc5b57eea{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pc5b57eea__overlay{padding:5px 0px 5px 0px !important;}.pc5b57eea .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc5b57eea{margin:0px 0px 20px 0px !important;}.pc5b57eea .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc5b57eea{margin:0px 0px 20px 0px !important;}.pc5b57eea .pc-heading{font-size:20px;}}","content":"Assessment","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc5b57eea" data-block-id="5b57eea"><div class="pc5b57eea__overlay"><h2 class="pc-heading">Assessment</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"39f5d42","css":".pc39f5d42{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 40px 0px !important;}.pc39f5d42__overlay{padding:0px 0px 0px 0px !important;}.pc39f5d42 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc39f5d42 .pc-paragraph{font-size:14px;}}","content":"Questions and discussions regarding this proposal would be handled by \u003cbr\u003eour team lead. We will be looking forward to attending to any of your \u003cbr\u003einquiries. The company’s phone numbers and email addresses are \u003cbr\u003eattached.\u003cbr\u003e\u003cbr\u003eAs soon as you approve the proposal, we are ready to meet. This would \u003cbr\u003eenable us to set dates and decide when to kick-off the project.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"40px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc39f5d42" data-block-id="39f5d42"><div class="pc39f5d42__overlay"><p class="pc-paragraph">Questions and discussions regarding this proposal would be handled by <br>our team lead. We will be looking forward to attending to any of your <br>inquiries. The company’s phone numbers and email addresses are <br>attached.<br><br>As soon as you approve the proposal, we are ready to meet. This would <br>enable us to set dates and decide when to kick-off the project.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"de0ad5c","css":".pcde0ad5c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pcde0ad5c__overlay{padding:5px 0px 5px 0px !important;}.pcde0ad5c .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcde0ad5c{margin:0px 0px 20px 0px !important;}.pcde0ad5c .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcde0ad5c{margin:0px 0px 20px 0px !important;}.pcde0ad5c .pc-heading{font-size:20px;}}","content":"Implementation Milestones","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcde0ad5c" data-block-id="de0ad5c"><div class="pcde0ad5c__overlay"><h2 class="pc-heading">Implementation Milestones</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/table {"uniqueId":"2b3c710","css":".pc2b3c710{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc2b3c710__overlay{padding:0px 0px 0px 0px !important;}.pc2b3c710 .pc-table thead th{background-color:#d1efeb;color:#000000;font-weight:700;padding:4px 0px 4px 8px;text-align:left;}.pc2b3c710 .pc-table{font-size:11px;}.pc2b3c710 .pc-table tbody tr:nth-child(odd) td{background-color:#f1fefc;color:#000000;}.pc2b3c710 .pc-table tbody tr:nth-child(even) td{background-color:#ffffff;}.pc2b3c710 .pc-table tbody td{font-weight:400;padding:8px 0 8px 8px;text-align:left;}","fontSize":11,"head":[{"cells":[{"content":"Daily responsiblities","tag":"th"},{"content":"Weekly responsibilities","tag":"th"},{"content":"Monthly responsibilities","tag":"th"}]}],"body":[{"cells":[{"content":"One Facebook post","tag":"td"},{"content":"One YouTube video","tag":"td"},{"content":"One animation video","tag":"td"}]},{"cells":[{"content":"One Twitter (X) post","tag":"td"},{"content":"One Tiktok video","tag":"td"},{"content":"One cartoon video","tag":"td"}]},{"cells":[{"content":"One LinkedIn post","tag":"td"},{"content":"One YouTube short","tag":"td"},{"content":"Analytics report","tag":"td"}]},{"cells":[{"content":"","tag":"td"},{"content":"One Facebook reel","tag":"td"},{"content":"Plan for next month","tag":"td"}]},{"cells":[{"content":"","tag":"td"},{"content":"One Facebook content","tag":"td"},{"content":"Upcoming trend post","tag":"td"}]},{"cells":[{"content":"","tag":"td"},{"content":"One Instagram video","tag":"td"},{"content":"One meme post","tag":"td"}]}],"headerFontWeight":"700","headerPadding":{"top":"4px","right":"0px","bottom":"4px","left":"8px"},"headerBackground":"#d1efeb","headerColor":"#000000","bodyBackgroundOdd":"#f1fefc","bodyBackgroundEven":"#ffffff","bodyColorOdd":"#000000","bodyPadding":{"top":"8px","bottom":"8px","left":"8px"}} -->
<div class="wp-block-asphalt-proposal-manager-table pc2b3c710" data-block-id="2b3c710"><div class="pc2b3c710__overlay"><table class="pc-table"><thead><tr><th>Daily responsiblities</th><th>Weekly responsibilities</th><th>Monthly responsibilities</th></tr></thead><tbody><tr><td>One Facebook post</td><td>One YouTube video</td><td>One animation video</td></tr><tr><td>One Twitter (X) post</td><td>One Tiktok video</td><td>One cartoon video</td></tr><tr><td>One LinkedIn post</td><td>One YouTube short</td><td>Analytics report</td></tr><tr><td></td><td>One Facebook reel</td><td>Plan for next month</td></tr><tr><td></td><td>One Facebook content</td><td>Upcoming trend post</td></tr><tr><td></td><td>One Instagram video</td><td>One meme post</td></tr></tbody></table></div></div>
<!-- /wp:asphalt-proposal-manager/table -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"991b3a3","css":".pc991b3a3{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:32px 0px 23px 0px !important;}.pc991b3a3__overlay{padding:5px 0px 5px 0px !important;}.pc991b3a3 .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc991b3a3{margin:0px 0px 20px 0px !important;}.pc991b3a3 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc991b3a3{margin:0px 0px 20px 0px !important;}.pc991b3a3 .pc-heading{font-size:20px;}}","content":"Goals and Outlook","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"32px","right":"0px","bottom":"23px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc991b3a3" data-block-id="991b3a3"><div class="pc991b3a3__overlay"><h2 class="pc-heading">Goals and Outlook</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"d8561b8","css":".pcd8561b8{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 40px 0px !important;}.pcd8561b8__overlay{padding:0px 0px 0px 0px !important;}.pcd8561b8 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcd8561b8 .pc-paragraph{font-size:14px;}}","content":"We also aim to drive higher conversion rates by implementing data-driven strategies and optimizing our content based on performance analytics.\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eThis includes setting measurable objectives such as achieving a 15% \u003cbr\u003eincrease in website traffic from social media channels and a 10% boost.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"40px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcd8561b8" data-block-id="d8561b8"><div class="pcd8561b8__overlay"><p class="pc-paragraph">We also aim to drive higher conversion rates by implementing data-driven strategies and optimizing our content based on performance analytics.<br><br><br>This includes setting measurable objectives such as achieving a 15% <br>increase in website traffic from social media channels and a 10% boost.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"c183102","css":".pcc183102{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pcc183102__overlay{padding:50px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pcc183102__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pcc183102__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"50px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pcc183102" data-block-id="c183102"><div class="pcc183102__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"2439e68","css":".pc2439e68{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pc2439e68__overlay{padding:5px 0px 5px 0px !important;}.pc2439e68 .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc2439e68{margin:0px 0px 20px 0px !important;}.pc2439e68 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc2439e68{margin:0px 0px 20px 0px !important;}.pc2439e68 .pc-heading{font-size:20px;}}","content":"Our Team","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc2439e68" data-block-id="2439e68"><div class="pc2439e68__overlay"><h2 class="pc-heading">Our Team</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"954a825","css":".pc954a825{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 40px 0px !important;}.pc954a825__overlay{padding:0px 0px 0px 0px !important;}.pc954a825 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc954a825 .pc-paragraph{font-size:14px;}}","content":"We aim to showcase the strength and expertise of the dedicated \u003cbr\u003eprofessionals driving our social media strategy. Our team is composed of \u003cbr\u003ehighly skilled individuals with diverse backgrounds in digital marketing, \u003cbr\u003econtent creation, graphic design, and data analytics. This diversity allows \u003cbr\u003eus to approach our social media efforts with a comprehensive and well-\u003cbr\u003erounded perspective.\u003cbr\u003e\u003cbr\u003e\u003cbr\u003e\u003cbr\u003e\u003cbr\u003e\u003cbr\u003eOur team is committed to delivering exceptional results through \u003cbr\u003einnovative strategies and a deep understanding of the latest social media \u003cbr\u003etrends. Each member brings a unique set of skills and insights, enabling us \u003cbr\u003eto create engaging, high-quality content that resonates with our target \u003cbr\u003eaudience.\u003cbr\u003eOur content creators and graphic designers work closely to produce \u003cbr\u003evisually appealing and impactful posts, while our digital marketing \u003cbr\u003eexperts develop targeted campaigns that drive engagement and growth.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"40px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc954a825" data-block-id="954a825"><div class="pc954a825__overlay"><p class="pc-paragraph">We aim to showcase the strength and expertise of the dedicated <br>professionals driving our social media strategy. Our team is composed of <br>highly skilled individuals with diverse backgrounds in digital marketing, <br>content creation, graphic design, and data analytics. This diversity allows <br>us to approach our social media efforts with a comprehensive and well-<br>rounded perspective.<br><br><br><br><br><br>Our team is committed to delivering exceptional results through <br>innovative strategies and a deep understanding of the latest social media <br>trends. Each member brings a unique set of skills and insights, enabling us <br>to create engaging, high-quality content that resonates with our target <br>audience.<br>Our content creators and graphic designers work closely to produce <br>visually appealing and impactful posts, while our digital marketing <br>experts develop targeted campaigns that drive engagement and growth.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:image {"id":66,"sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"right":"180px","left":"180px"}}}} -->
<figure class="wp-block-image size-full" style="margin-right:180px;margin-left:180px"><img src="<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/user.png') ) ?>" alt="" class="wp-image-66"/></figure>
<!-- /wp:image -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"5962b28","css":".pc5962b28{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc5962b28__overlay{padding:0px 0px 0px 0px !important;}.pc5962b28 .pc-heading{text-align:center;color:#000000;font-size:14px;font-family:Kadwa;font-weight:700;}","content":"Jane Doe","alignment":"center","fontSize":14,"fontWeight":"700","fontFamily":"Kadwa"} -->
<div class="wp-block-asphalt-proposal-manager-heading pc5962b28" data-block-id="5962b28"><div class="pc5962b28__overlay"><h2 class="pc-heading">Jane Doe</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"94af323","css":".pc94af323{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc94af323__overlay{padding:0px 0px 0px 0px !important;}.pc94af323 .pc-paragraph{text-align:center;color:#000000;font-size:14px;font-weight:400;}","content":"Founder, PropoHunt","alignment":"center"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc94af323" data-block-id="94af323"><div class="pc94af323__overlay"><p class="pc-paragraph">Founder, PropoHunt</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"3d86b74","css":".pc3d86b74{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc3d86b74__overlay{padding:50px 36px 300px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc3d86b74__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc3d86b74__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"50px","right":"36px","bottom":"300px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc3d86b74" data-block-id="3d86b74"><div class="pc3d86b74__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"ce02aa1","css":".pcce02aa1{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pcce02aa1__overlay{padding:5px 0px 5px 0px !important;}.pcce02aa1 .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcce02aa1{margin:0px 0px 20px 0px !important;}.pcce02aa1 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcce02aa1{margin:0px 0px 20px 0px !important;}.pcce02aa1 .pc-heading{font-size:20px;}}","content":"Billing","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcce02aa1" data-block-id="ce02aa1"><div class="pcce02aa1__overlay"><h2 class="pc-heading">Billing</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/pricing {"uniqueId":"1021fc1","css":".pc1021fc1{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc1021fc1__overlay{padding:0px 0px 0px 0px !important;}.pc1021fc1 table thead th{background-color:#ffffff;color:#000000;font-weight:500;padding:8px 14px 8px 14px;font-family:Readex Pro;font-size:14px;}.pc1021fc1 table tbody tr td{border-bottom-color:#E1E1E1;padding:15px 15px 15px 15px;}.pc1021fc1 table tbody tr td .pc-pricing-item-title{color:#000000;font-family:Readex Pro;font-weight:400;font-size:16px;}.pc1021fc1 table tbody tr td .pc-pricing-item-wrapper{margin:0px 0px 5px 0px;}.pc1021fc1 table tbody tr td .pc-pricing-item-description{color:#000000;font-family:Readex Pro;font-weight:300;font-size:14px;}.pc1021fc1 table tbody tr td.pc-pricing-column{color:#000000;font-family:Readex Pro;font-weight:300;font-size:16px;}.pc1021fc1 table tfoot tr.pc-subtotal-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:9px 0 0 0;}.pc1021fc1 table tfoot tr.pc-adjustments-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:10px 0 0 0;}.pc1021fc1 table tfoot tr.pc-total-row td{font-family:Readex Pro;font-weight:400;font-size:20px;padding:10px 0 0 0;}","tableTitle":"Project Billing","itemColumnLabel":"Pricing Items","items":[{"title":"Social media contentsg","description":"All social media platforms","price":1245,"quantity":43,"isChecked":true},{"title":"Video production","description":"Only for YouTube \u0026amp; Tiktok","price":1245,"quantity":43,"isChecked":true},{"title":"Strategy \u0026amp; plan","description":"For a holistic approach","price":1245,"quantity":43,"isChecked":false}],"showSubtotal":true,"showTotal":true,"headerFontWeight":"500","headerFontFamily":"Readex Pro","headerFontSize":14,"headerPadding":{"top":"8px","right":"14px","bottom":"8px","left":"14px"},"headerBackground":"#ffffff","headerColor":"#000000","titleColor":"#000000","titleFontFamily":"Readex Pro","titleFontWeight":"400","titleFontSize":16,"descriptionColor":"#000000","descriptionFontFamily":"Readex Pro","descriptionFontWeight":"300","descriptionFontSize":14,"pricingColor":"#000000","pricingFontFamily":"Readex Pro","pricingFontWeight":"300","pricingFontSize":16,"subtotalFontFamily":"Readex Pro","subtotalFontWeight":"400","subtotalFontSize":16,"subtotalMargin":{"top":"9px"},"adjustmentsFontFamily":"Readex Pro","adjustmentsFontWeight":"400","adjustmentsFontSize":16,"adjustmentsMargin":{"top":"10px"},"totalFontFamily":"Readex Pro","totalFontWeight":"400","totalFontSize":20,"totalMargin":{"top":"10px"},"background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"b0989c6","css":".pcb0989c6{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pcb0989c6__overlay{padding:52px 36px 0px 24px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pcb0989c6__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pcb0989c6__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"52px","right":"36px","bottom":"0px","left":"24px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pcb0989c6" data-block-id="b0989c6"><div class="pcb0989c6__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"16b0919","css":".pc16b0919{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pc16b0919__overlay{padding:5px 0px 5px 0px !important;}.pc16b0919 .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc16b0919{margin:0px 0px 20px 0px !important;}.pc16b0919 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc16b0919{margin:0px 0px 20px 0px !important;}.pc16b0919 .pc-heading{font-size:20px;}}","content":"Terms and Conditions","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"5px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc16b0919" data-block-id="16b0919"><div class="pc16b0919__overlay"><h2 class="pc-heading">Terms and Conditions</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"b860ae2","css":".pcb860ae2{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcb860ae2__overlay{padding:0px 0px 0px 0px !important;}.pcb860ae2 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pcb860ae2" data-block-id="b860ae2"><div class="pcb860ae2__overlay"><ul><li>Acceptance of Terms: By using our services, you agree to comply with and be bound by these terms and conditions.</li><li>Changes to Terms: We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting.</li><li>User Responsibilities:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">You must provide accurate and current information  during                         registration.</li>
<!-- /wp:list-item -->

<!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">You are responsible for maintaining the confidentiality of your account information.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"e8e3e39","css":".pce8e3e39{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pce8e3e39__overlay{padding:0px 0px 0px 0px !important;}.pce8e3e39 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pce8e3e39" data-block-id="e8e3e39"><div class="pce8e3e39__overlay"><ul><li>Content Ownership:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">All content provided by us is owned by our company and is protected by intellectual property laws.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"444ac00","css":".pc444ac00{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc444ac00__overlay{padding:0px 0px 0px 0px !important;}.pc444ac00 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc444ac00" data-block-id="444ac00"><div class="pc444ac00__overlay"><ul><li>User-Generated Content:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">Users may submit content, which remains their property but grants us a          non-exclusive license to use, modify, and display it.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"9fc4b9c","css":".pc9fc4b9c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc9fc4b9c__overlay{padding:0px 0px 0px 0px !important;}.pc9fc4b9c li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc9fc4b9c" data-block-id="9fc4b9c"><div class="pc9fc4b9c__overlay"><ul><li>Privacy:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">We are committed to protecting your privacy and will handle all                      personal data in accordance with our Privacy Policy.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"615d3eb","css":".pc615d3eb{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc615d3eb__overlay{padding:0px 0px 0px 0px !important;}.pc615d3eb li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc615d3eb" data-block-id="615d3eb"><div class="pc615d3eb__overlay"><ul><li>Disclaimers:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">Our services are provided on an "as-is" basis without warranties of any             kind.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"343f222","css":".pc343f222{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc343f222__overlay{padding:0px 0px 0px 0px !important;}.pc343f222 li{text-align:left;color:#000000;font-size:14px;font-weight:400;}"} -->
<div class="wp-block-asphalt-proposal-manager-list pc343f222" data-block-id="343f222"><div class="pc343f222__overlay"><ul><li>Limitation of Liability:</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">We are not liable for any direct, indirect, incidental, or consequential     damages arising from your use of our services.</li>
<!-- /wp:list-item -->

<!-- wp:list-item {"style":{"typography":{"fontSize":"14px"},"elements":{"link":{"color":{"text":"#000000"}}},"color":{"text":"#000000"}}} -->
<li class="has-text-color has-link-color" style="color:#000000;font-size:14px">Our liability is limited to the maximum extent permitted by law.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"2df3d4d","css":".pc2df3d4d{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc2df3d4d__overlay{padding:81px 36px 495px 40px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc2df3d4d__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc2df3d4d__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/3/social-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"81px","right":"36px","bottom":"495px","left":"40px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc2df3d4d" data-block-id="2df3d4d"><div class="pc2df3d4d__overlay"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"69c3edd","css":".pc69c3edd{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 30px 0px !important;}.pc69c3edd__overlay{padding:0px 0px 5px 0px !important;}.pc69c3edd .pc-heading{text-align:left;color:#000000;font-size:24px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc69c3edd{margin:0px 0px 20px 0px !important;}.pc69c3edd .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc69c3edd{margin:0px 0px 20px 0px !important;}.pc69c3edd .pc-heading{font-size:20px;}}","content":"Accept \u0026amp; Sign","fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"700","fontFamily":"Kadwa","background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"0px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"30px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc69c3edd" data-block-id="69c3edd"><div class="pc69c3edd__overlay"><h2 class="pc-heading">Accept &amp; Sign</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"0246001","css":".pc0246001{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc0246001__overlay{padding:0px 0px 0px 0px !important;}.pc0246001 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc0246001 .pc-paragraph{font-size:14px;}}","content":"I am writing to express my interest in the UX Designer position at [Company Name], as advertised on [where you found the job posting]. With seven years of experience in UX design and a passion.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc0246001" data-block-id="0246001"><div class="pc0246001__overlay"><p class="pc-paragraph">I am writing to express my interest in the UX Designer position at [Company Name], as advertised on [where you found the job posting]. With seven years of experience in UX design and a passion.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"89bf94c","css":".pc89bf94c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:40px 0px 0px 0px !important;max-width:1024px;}.pc89bf94c__overlay{padding:0px 0px 0px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:space-between;}","display":"flex","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"40px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc89bf94c" data-block-id="89bf94c"><div class="pc89bf94c__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"8918f36","css":".pc8918f36{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pc8918f36__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pc8918f36" data-block-id="8918f36"><div class="pc8918f36__overlay"><!-- wp:asphalt-proposal-manager/signature {"uniqueId":"dce3bdf","placeholder":"Signature","css":".pcdce3bdf{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;width:200px;}.pcdce3bdf__overlay{padding:16px 10px 16px 10px !important;}.pcdce3bdf .signature-content{text-align:center;}","fontSize":14,"fontFamily":"Readex Pro","padding":{"top":"16px","right":"10px","bottom":"16px","left":"10px"},"alignment":"center"} /-->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"bedf138","css":".pcbedf138{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:10px 0px 4px 0px !important;}.pcbedf138__overlay{padding:0px 0px 0px 0px !important;}.pcbedf138 .pc-sender-name{text-align:left;color:#000000;font-size:13px;font-family:Kadwa;font-weight:400;}","content":"Signature","fontSize":13,"fontFamily":"Kadwa","margin":{"top":"10px","right":"0px","bottom":"4px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/sender-company {"uniqueId":"0c61c1e","css":".pc0c61c1e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc0c61c1e__overlay{padding:0px 0px 0px 0px !important;}.pc0c61c1e .pc-sender-company{text-align:left;color:#000000;font-size:13px;font-family:Kadwa;font-weight:400;}","content":"Sender company","fontSize":13,"fontFamily":"Kadwa"} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"50808f0","css":".pc50808f0{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pc50808f0__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pc50808f0" data-block-id="50808f0"><div class="pc50808f0__overlay"><!-- wp:asphalt-proposal-manager/signature {"uniqueId":"bcd8ed9","userType":"client","placeholder":"Signature","css":".pcbcd8ed9{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;width:200px;}.pcbcd8ed9__overlay{padding:16px 10px 16px 10px !important;}.pcbcd8ed9 .signature-content{text-align:center;}","fontSize":14,"fontFamily":"Readex Pro","padding":{"top":"16px","right":"10px","bottom":"16px","left":"10px"},"alignment":"center"} /-->

<!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"69fea3c","css":".pc69fea3c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:10px 0px 4px 0px !important;}.pc69fea3c__overlay{padding:0px 0px 0px 0px !important;}.pc69fea3c .pc-client-name{text-align:left;color:#000000;font-size:12px;font-family:Kadwa;font-weight:400;}","content":"Client Name","fontSize":12,"fontFamily":"Kadwa","margin":{"top":"10px","right":"0px","bottom":"4px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/client-company {"uniqueId":"87301fa","css":".pc87301fa{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc87301fa__overlay{padding:0px 0px 0px 0px !important;}.pc87301fa .pc-client-company{text-align:left;color:#000000;font-size:13px;font-family:Kadwa;font-weight:400;}","content":"Client company","fontSize":13,"fontFamily":"Kadwa"} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->