<?php defined( 'ABSPATH' ) || exit; ?>
<!-- wp:asphalt-proposal-manager/container {"uniqueId":"014f05e","css":".pc014f05e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:100%;}.pc014f05e__overlay{padding:36px 0px 0px 0px !important;display:flex;flex-direction:column;align-items:center;justify-content:center;}","display":"flex","flexDirection":"column","justifyContent":"center","maxWidth":{"type":"full-width","value":"100%"},"padding":{"top":"36px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc014f05e" data-block-id="014f05e"><div class="pc014f05e__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"52337d7","css":".pc52337d7{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-cover-bg.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc52337d7__overlay{padding:36px 36px 36px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc52337d7__overlay{padding:36px 36px 36px 36px !important;}}@media screen and (max-width: 767px){.pc52337d7__overlay{padding:18px 18px 18px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"http://localhost:8001/wp-content/plugins/asphalt-proposal-manager/assets/templates/1/proposal-cover-bg.webp"},"padding":{"top":"36px","right":"36px","bottom":"36px","left":"36px"},"paddingTablet":{"top":"36px","right":"36px","bottom":"36px","left":"36px"},"paddingMobile":{"top":"18px","right":"18px","bottom":"18px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc52337d7" data-block-id="52337d7"><div class="pc52337d7__overlay"><!-- wp:columns {"isStackedOnMobile":false,"className":"is-style-default"} -->
<div class="wp-block-columns is-not-stacked-on-mobile is-style-default"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"a208150","css":".pca208150{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pca208150__overlay{padding:0px 0px 0px 0px !important;}.pca208150 .pc-heading{text-align:left;color:#000000;font-size:18px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pca208150 .pc-heading{font-size:16px;}}@media screen and (max-width: 767px){.pca208150 .pc-heading{font-size:16px;}}","content":"Kanatkyzy \u003cbr\u003eAina","fontSize":18,"fontSizeTablet":16,"fontSizeMobile":16,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-heading pca208150" data-block-id="a208150"><div class="pca208150__overlay"><h2 class="pc-heading">Kanatkyzy <br>Aina</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"7763927","css":".pc7763927{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc7763927__overlay{padding:0px 0px 0px 0px !important;}.pc7763927 .pc-heading{text-align:right;color:#000000;font-size:18px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc7763927 .pc-heading{text-align:right;font-size:16px;}}@media screen and (max-width: 767px){.pc7763927 .pc-heading{text-align:right;font-size:16px;}}","content":"2026","htmlTag":"h3","alignment":"right","alignmentTablet":"right","alignmentMobile":"right","fontSize":18,"fontSizeTablet":16,"fontSizeMobile":16,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-heading pc7763927" data-block-id="7763927"><div class="pc7763927__overlay"><h3 class="pc-heading">2026</h3></div></div>
<!-- /wp:asphalt-proposal-manager/heading --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"5afeddd","css":".pc5afeddd{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:466px;}.pc5afeddd__overlay{padding:180px 5px 120px 5px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc5afeddd__overlay{padding:83px 0px 70px 0px !important;}}@media screen and (max-width: 767px){.pc5afeddd__overlay{padding:37px 0px 37px 0px !important;}}","maxWidth":{"type":"custom","value":466},"alignment":"left","padding":{"top":"180px","right":"5px","bottom":"120px","left":"5px"},"paddingTablet":{"top":"83px","right":"0px","bottom":"70px","left":"0px"},"paddingMobile":{"top":"37px","right":"0px","bottom":"37px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc5afeddd" data-block-id="5afeddd"><div class="pc5afeddd__overlay"><!-- wp:asphalt-proposal-manager/proposal-title {"uniqueId":"e61b763","css":".pce61b763{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pce61b763__overlay{padding:0px 0px 0px 0px !important;}.pce61b763 .pc-proposal-title{text-align:left;color:#000000;font-size:64px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pce61b763{margin:0px 0px 10px 0px !important;}.pce61b763 .pc-proposal-title{font-size:48px;}}@media screen and (max-width: 767px){.pce61b763{margin:0px 0px 10px 0px !important;}}","content":"Project Proposal","fontSize":64,"fontSizeTablet":48,"fontWeight":"500","fontFamily":"Readex Pro","marginTablet":{"top":"0px","right":"0px","bottom":"10px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"10px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"76bcd14","css":".pc76bcd14{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:10px 0px 0px 0px !important;}.pc76bcd14__overlay{padding:0px 0px 0px 0px !important;}.pc76bcd14 .pc-paragraph{text-align:left;color:#000000;font-size:20px;font-family:Readex Pro;font-weight:300;}","content":"February 6, 2026","fontSize":20,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"10px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc76bcd14" data-block-id="76bcd14"><div class="pc76bcd14__overlay"><p class="pc-paragraph">February 6, 2026</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:columns {"className":"is-style-default"} -->
<div class="wp-block-columns is-style-default"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"dfb1d5d","css":".pcdfb1d5d{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 14px 0px !important;}.pcdfb1d5d__overlay{padding:0px 0px 0px 0px !important;}.pcdfb1d5d .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pcdfb1d5d__overlay{padding:0px 0px 5px 0px !important;}}","content":"Created for","fontWeight":"700","fontFamily":"Kadwa","paddingTablet":{"top":"0px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"14px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcdfb1d5d" data-block-id="dfb1d5d"><div class="pcdfb1d5d__overlay"><p class="pc-paragraph">Created for</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"8300c3d","css":".pc8300c3d{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc8300c3d__overlay{padding:0px 0px 0px 0px !important;}.pc8300c3d .pc-client-name{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc8300c3d .pc-client-name{font-size:20px;}}@media screen and (max-width: 767px){.pc8300c3d .pc-client-name{font-size:20px;}}","content":"Client name","fontSizeTablet":20,"fontSizeMobile":20,"fontWeight":"300","fontFamily":"Readex Pro"} /-->

<!-- wp:asphalt-proposal-manager/client-email {"uniqueId":"7b07d32","css":".pc7b07d32{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc7b07d32__overlay{padding:0px 0px 0px 0px !important;}.pc7b07d32 .pc-client-email{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc7b07d32 .pc-client-email{font-size:14px;}}@media screen and (max-width: 767px){.pc7b07d32 .pc-client-email{font-size:14px;}}","content":"clientemail@example.com","fontSize":14,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} /-->

<!-- wp:asphalt-proposal-manager/client-company {"uniqueId":"a570b18","css":".pca570b18{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:18px 0px 0px 0px !important;}.pca570b18__overlay{padding:0px 0px 0px 0px !important;}.pca570b18 .pc-client-company{text-align:left;color:#000000;font-size:16px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pca570b18{margin:1px 0px 0px 0px !important;}}@media screen and (max-width: 767px){.pca570b18{margin:10px 0px 0px 0px !important;}.pca570b18 .pc-client-company{font-size:16px;}}","content":"Client company","fontSizeMobile":16,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"18px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"1px","right":"0px","bottom":"0px","left":"0px"},"marginMobile":{"top":"10px","right":"0px","bottom":"0px","left":"0px"}} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"6677f0b","css":".pc6677f0b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 14px 0px !important;}.pc6677f0b__overlay{padding:0px 0px 0px 0px !important;}.pc6677f0b .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Kadwa;font-weight:700;}@media screen and (max-width: 1023px){.pc6677f0b__overlay{padding:0px 0px 5px 0px !important;}}","content":"Created by","fontWeight":"700","fontFamily":"Kadwa","paddingTablet":{"top":"0px","right":"0px","bottom":"5px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"14px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc6677f0b" data-block-id="6677f0b"><div class="pc6677f0b__overlay"><p class="pc-paragraph">Created by</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"6ab48a8","css":".pc6ab48a8{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc6ab48a8__overlay{padding:0px 0px 0px 0px !important;}.pc6ab48a8 .pc-sender-name{text-align:left;color:#000000;font-size:16px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc6ab48a8 .pc-sender-name{font-size:20px;}}@media screen and (max-width: 767px){.pc6ab48a8 .pc-sender-name{font-size:20px;}}","content":"Sender name","fontSizeTablet":20,"fontSizeMobile":20,"fontWeight":"300","fontFamily":"Readex Pro"} /-->

<!-- wp:asphalt-proposal-manager/sender-email {"uniqueId":"de5e40c","css":".pcde5e40c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcde5e40c__overlay{padding:0px 0px 0px 0px !important;}.pcde5e40c .pc-sender-email{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pcde5e40c .pc-sender-email{font-size:14px;}}@media screen and (max-width: 767px){.pcde5e40c .pc-sender-email{font-size:14px;}}","content":"senderemail@example.com","fontSize":14,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} /-->

<!-- wp:asphalt-proposal-manager/sender-company {"uniqueId":"9670d42","css":".pc9670d42{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pc9670d42__overlay{padding:0px 0px 0px 0px !important;}.pc9670d42 .pc-sender-company{text-align:left;color:#000000;font-size:16px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc9670d42{margin:5px 0px 0px 0px !important;}.pc9670d42 .pc-sender-company{font-size:15px;}}@media screen and (max-width: 767px){.pc9670d42{margin:10px 0px 0px 0px !important;}.pc9670d42 .pc-sender-company{font-size:16px;}}","content":"Sender company","fontSizeTablet":15,"fontSizeMobile":16,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"5px","right":"0px","bottom":"0px","left":"0px"},"marginMobile":{"top":"10px","right":"0px","bottom":"0px","left":"0px"}} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cc16e00","css":".pccc16e00{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccc16e00__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccc16e00__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccc16e00__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccc16e00" data-block-id="cc16e00"><div class="pccc16e00__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"ce4988b","css":".pcce4988b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 22px 0px !important;}.pcce4988b__overlay{padding:0px 0px 0px 0px !important;}.pcce4988b .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcce4988b{margin:0px 0px 20px 0px !important;}.pcce4988b .pc-heading{font-size:20px;}}","content":"Introduction","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"0px","right":"0px","bottom":"20px","left":"0px"},"marginMobile":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcce4988b" data-block-id="ce4988b"><div class="pcce4988b__overlay"><h2 class="pc-heading">Introduction</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"78a3519","css":".pc78a3519{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:1024px;}.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:flex-start;}@media screen and (max-width: 1023px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}@media screen and (max-width: 767px){.pc78a3519__overlay{padding:0px 0px 12px 0px !important;display:inline-flex;}}","display":"flex","displayTablet":"inline-flex","displayMobile":"inline-flex","justifyContent":"flex-start","padding":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingTablet":{"top":"0px","right":"0px","bottom":"12px","left":"0px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"12px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc78a3519" data-block-id="78a3519"><div class="pc78a3519__overlay"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"2dba7c8","css":".pc2dba7c8{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc2dba7c8__overlay{padding:0px 0px 0px 0px !important;}.pc2dba7c8 .pc-paragraph{text-align:left;color:#000000;font-size:13px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc2dba7c8 .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc2dba7c8 .pc-paragraph{font-size:14px;}}","content":"Dear","fontSize":13,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc2dba7c8" data-block-id="2dba7c8"><div class="pc2dba7c8__overlay"><p class="pc-paragraph">Dear</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"3680790","css":".pc3680790{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc3680790__overlay{padding:0px 0px 0px 3px !important;}.pc3680790 .pc-client-name{text-align:left;color:#000000;font-size:13px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc3680790__overlay{padding:0px 0px 0px 3px !important;}.pc3680790 .pc-client-name{font-size:14px;}}@media screen and (max-width: 767px){.pc3680790__overlay{padding:0px 0px 0px 3px !important;}.pc3680790 .pc-client-name{font-size:14px;}}","content":"Client name","fontSize":13,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","padding":{"top":"0px","right":"0px","bottom":"0px","left":"3px"},"paddingTablet":{"top":"0px","right":"0px","bottom":"0px","left":"3px"},"paddingMobile":{"top":"0px","right":"0px","bottom":"0px","left":"3px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"1089bdc","css":".pc1089bdc{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc1089bdc__overlay{padding:0px 0px 0px 0px !important;}.pc1089bdc .pc-paragraph{text-align:left;color:#000000;font-size:13px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc1089bdc .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc1089bdc .pc-paragraph{font-size:14px;}}","content":"Our proposed project aims to address [briefly describe the main focus or subject of your project]. In today’s rapidly evolving landscape, this project holds significant importance due to [mention the broader context or relevance]. By tackling [the problem or challenge], we intend to [state the objectives or research questions].\u003cbr\u003e\u003cbr\u003eTo provide necessary context, it’s essential to understand [provide relevant background information]. [Discuss any existing challenges or gaps in the field.] Our project will operate within [describe the specific context or environment].\u003cbr\u003e\u003cbr\u003eAt the heart of our project lies the problem of [clearly define the issue]. Our research questions include [list the specific questions you aim to explore]. By achieving these objectives, we hope to [mention the positive impact or outcomes].\u003cbr\u003e\u003cbr\u003eOur proposed approach involves [briefly describe the methodology or steps you’ll take]. We plan to [outline the specific methods, tools, or techniques]. By following this approach, we aim to [mention the expected outcomes or benefits].\u003cbr\u003e\u003cbr\u003eOur project holds great promise for [describe the relevant stakeholders or beneficiaries]. By addressing [the problem or challenge], we anticipate [mention the positive impact or outcomes]. This project aligns with [any relevant initiatives or goals] and contributes to [broader societal or organizational objectives]","fontSize":13,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc1089bdc" data-block-id="1089bdc"><div class="pc1089bdc__overlay"><p class="pc-paragraph">Our proposed project aims to address [briefly describe the main focus or subject of your project]. In today’s rapidly evolving landscape, this project holds significant importance due to [mention the broader context or relevance]. By tackling [the problem or challenge], we intend to [state the objectives or research questions].<br><br>To provide necessary context, it’s essential to understand [provide relevant background information]. [Discuss any existing challenges or gaps in the field.] Our project will operate within [describe the specific context or environment].<br><br>At the heart of our project lies the problem of [clearly define the issue]. Our research questions include [list the specific questions you aim to explore]. By achieving these objectives, we hope to [mention the positive impact or outcomes].<br><br>Our proposed approach involves [briefly describe the methodology or steps you’ll take]. We plan to [outline the specific methods, tools, or techniques]. By following this approach, we aim to [mention the expected outcomes or benefits].<br><br>Our project holds great promise for [describe the relevant stakeholders or beneficiaries]. By addressing [the problem or challenge], we anticipate [mention the positive impact or outcomes]. This project aligns with [any relevant initiatives or goals] and contributes to [broader societal or organizational objectives]</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"76b473e","css":".pc76b473e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:20px 0px 0px 0px !important;}.pc76b473e__overlay{padding:0px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc76b473e{margin:18px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{font-size:14px;}}@media screen and (max-width: 767px){.pc76b473e{margin:18px 0px 0px 0px !important;}.pc76b473e .pc-paragraph{font-size:14px;}}","content":"UX/UI Designer","fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"20px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"18px","right":"0px","bottom":"0px","left":"0px"},"marginMobile":{"top":"18px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc76b473e" data-block-id="76b473e"><div class="pc76b473e__overlay"><p class="pc-paragraph">UX/UI Designer</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"caa8abc","css":".pccaa8abc{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pccaa8abc__overlay{padding:0px 0px 0px 0px !important;}.pccaa8abc .pc-sender-name{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pccaa8abc .pc-sender-name{font-size:14px;}}@media screen and (max-width: 767px){.pccaa8abc .pc-sender-name{font-size:14px;}}","content":"Sender name","fontSize":14,"fontSizeTablet":14,"fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"cdd0ef3","css":".pccdd0ef3{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pccdd0ef3__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pccdd0ef3__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pccdd0ef3__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pccdd0ef3" data-block-id="cdd0ef3"><div class="pccdd0ef3__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"f0cbff9","css":".pcf0cbff9{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 22px 0px !important;}.pcf0cbff9__overlay{padding:0px 0px 0px 0px !important;}.pcf0cbff9 .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pcf0cbff9__overlay{padding:0px 0px 0px 0px !important;}.pcf0cbff9{margin:0 0 20px 0 !important;}.pcf0cbff9 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcf0cbff9{margin:0 0 20px 0 !important;}.pcf0cbff9 .pc-heading{font-size:20px;}}","content":"Objective","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","paddingTablet":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"bottom":"20px"},"marginMobile":{"bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcf0cbff9" data-block-id="f0cbff9"><div class="pcf0cbff9__overlay"><h2 class="pc-heading">Objective</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"6258c03","css":".pc6258c03{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc6258c03__overlay{padding:0px 0px 0px 0px !important;}.pc6258c03 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}","content":"Based on the discussion we have had where you have shared your business and project specs, your goals, mission, and challenges, I have developed a vision of further work on the design that I feel will improve your marketing and identity.\u003cbr\u003e\u003cbr\u003eMy deliveries on this project are as follows:","fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc6258c03" data-block-id="6258c03"><div class="pc6258c03__overlay"><p class="pc-paragraph">Based on the discussion we have had where you have shared your business and project specs, your goals, mission, and challenges, I have developed a vision of further work on the design that I feel will improve your marketing and identity.<br><br>My deliveries on this project are as follows:</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/list {"uniqueId":"8e44c36","css":".pc8e44c36{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:20px 0px 0px 0px !important;}.pc8e44c36__overlay{padding:0px 0px 0px 0px !important;}.pc8e44c36 li{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc8e44c36{margin:20px 0 0 0 !important;}}@media screen and (max-width: 767px){.pc8e44c36{margin:20px 0 0 0 !important;}}","fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"20px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"20px"},"marginMobile":{"top":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-list pc8e44c36" data-block-id="8e44c36"><div class="pc8e44c36__overlay"><ul><li>Provide project for the website page. The page is to be designed for 3 end users: admins, external buyers, and sellers.</li><li>Provide project for the website page. The page is to be designed for individual sellers (see design request).</li><li>All projects will contain brand colors and styles, as well as the typography, icons, and logo, that you provided earlier.</li><li>As per the project brief and request, the design will follow a minimalistic design that will serve such functionalities as [logging in, availability to search and find content, booking a flight, choosing dates, rejecting or accepting the booking, etc.]</li></ul></div></div>
<!-- /wp:asphalt-proposal-manager/list -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"c6959c9","css":".pcc6959c9{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:40px 0px 22px 0px !important;}.pcc6959c9__overlay{padding:0px 0px 0px 0px !important;}.pcc6959c9 .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pcc6959c9{margin:30px 0 20px 0 !important;}.pcc6959c9 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pcc6959c9{margin:30px 0 18px 0 !important;}.pcc6959c9 .pc-heading{font-size:20px;}}","content":"Process Outlines","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","margin":{"top":"40px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"30px","bottom":"20px"},"marginMobile":{"top":"30px","bottom":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pcc6959c9" data-block-id="c6959c9"><div class="pcc6959c9__overlay"><h2 class="pc-heading">Process Outlines</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"c8f28ea","css":".pcc8f28ea{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcc8f28ea__overlay{padding:0px 0px 0px 0px !important;}.pcc8f28ea .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcc8f28ea .pc-paragraph{font-size:14px;}}","content":"In my work process, I use the Double Diamond approach. However, I will be glad to implement whichever method is used in your company so that this project will meet its objectives in an effective way.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcc8f28ea" data-block-id="c8f28ea"><div class="pcc8f28ea__overlay"><p class="pc-paragraph">In my work process, I use the Double Diamond approach. However, I will be glad to implement whichever method is used in your company so that this project will meet its objectives in an effective way.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"a3fc9df","css":".pca3fc9df{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pca3fc9df__overlay{padding:0px 0px 0px 0px !important;}.pca3fc9df .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 1023px){.pca3fc9df{margin:16px 0 0 0 !important;}}@media screen and (max-width: 767px){.pca3fc9df{margin:13px 0 0 0 !important;}}","content":"Phase 1. Discover","fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"16px"},"marginMobile":{"top":"13px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pca3fc9df" data-block-id="a3fc9df"><div class="pca3fc9df__overlay"><p class="pc-paragraph">Phase 1. Discover</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"96f0145","css":".pc96f0145{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 0px !important;}.pc96f0145__overlay{padding:0px 0px 0px 0px !important;}.pc96f0145 .pc-paragraph{text-align:left;color:#818181;font-size:14px;font-family:Readex Pro;font-weight:300;}","content":"Estimated duration: XX days","fontWeight":"300","fontFamily":"Readex Pro","color":"#818181","margin":{"top":"4px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc96f0145" data-block-id="96f0145"><div class="pc96f0145__overlay"><p class="pc-paragraph">Estimated duration: XX days</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"75045c2","css":".pc75045c2{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 24px !important;}.pc75045c2__overlay{padding:0px 0px 0px 0px !important;}.pc75045c2 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc75045c2{margin:4px 0 0 24px !important;}}@media screen and (max-width: 767px){.pc75045c2{margin:4px 0 0 18px !important;}}","content":"In the first stage, I will conduct competitive research as per the reference from the customer to understand and find out the best solutions that can be implemented in a new project.","fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"4px","right":"0px","bottom":"0px","left":"24px"},"marginTablet":{"top":"4px","left":"24px"},"marginMobile":{"top":"4px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc75045c2" data-block-id="75045c2"><div class="pc75045c2__overlay"><p class="pc-paragraph">In the first stage, I will conduct competitive research as per the reference from the customer to understand and find out the best solutions that can be implemented in a new project.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"29ef7ed","css":".pc29ef7ed{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pc29ef7ed__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pc29ef7ed__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pc29ef7ed__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc29ef7ed" data-block-id="29ef7ed"><div class="pc29ef7ed__overlay"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"b5cefe0","css":".pcb5cefe0{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pcb5cefe0__overlay{padding:0px 0px 0px 0px !important;}.pcb5cefe0 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 1023px){.pcb5cefe0{margin:16px 0 0 0 !important;}}@media screen and (max-width: 767px){.pcb5cefe0{margin:13px 0 0 0 !important;}}","content":"Phase 2. Define","fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"16px"},"marginMobile":{"top":"13px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcb5cefe0" data-block-id="b5cefe0"><div class="pcb5cefe0__overlay"><p class="pc-paragraph">Phase 2. Define</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"f2b48e3","css":".pcf2b48e3{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 0px !important;}.pcf2b48e3__overlay{padding:0px 0px 0px 0px !important;}.pcf2b48e3 .pc-paragraph{text-align:left;color:#818181;font-size:14px;font-family:Readex Pro;font-weight:300;}","content":"Estimated duration: XX days","fontWeight":"300","fontFamily":"Readex Pro","color":"#818181","margin":{"top":"4px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcf2b48e3" data-block-id="f2b48e3"><div class="pcf2b48e3__overlay"><p class="pc-paragraph">Estimated duration: XX days</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"78589c2","css":".pc78589c2{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 24px !important;}.pc78589c2__overlay{padding:0px 0px 0px 0px !important;}.pc78589c2 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc78589c2{margin:4px 0 0 24px !important;}}@media screen and (max-width: 767px){.pc78589c2{margin:4px 0 0 18px !important;}}","content":"After collecting information and insights from competitive research I will prepare a database which I will use to make further decisions on future project. At this stage, we will be able to think over the product strategy.","fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"4px","right":"0px","bottom":"0px","left":"24px"},"marginTablet":{"top":"4px","left":"24px"},"marginMobile":{"top":"4px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc78589c2" data-block-id="78589c2"><div class="pc78589c2__overlay"><p class="pc-paragraph">After collecting information and insights from competitive research I will prepare a database which I will use to make further decisions on future project. At this stage, we will be able to think over the product strategy.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"2eedb8e","css":".pc2eedb8e{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pc2eedb8e__overlay{padding:0px 0px 0px 0px !important;}.pc2eedb8e .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 1023px){.pc2eedb8e{margin:16px 0 0 0 !important;}}@media screen and (max-width: 767px){.pc2eedb8e{margin:13px 0 0 0 !important;}}","content":"Phase 3. Develop","fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"16px"},"marginMobile":{"top":"13px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc2eedb8e" data-block-id="2eedb8e"><div class="pc2eedb8e__overlay"><p class="pc-paragraph">Phase 3. Develop</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"7fbc712","css":".pc7fbc712{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 0px !important;}.pc7fbc712__overlay{padding:0px 0px 0px 0px !important;}.pc7fbc712 .pc-paragraph{text-align:left;color:#818181;font-size:14px;font-family:Readex Pro;font-weight:300;}","content":"Estimated duration: XX days","fontWeight":"300","fontFamily":"Readex Pro","color":"#818181","margin":{"top":"4px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc7fbc712" data-block-id="7fbc712"><div class="pc7fbc712__overlay"><p class="pc-paragraph">Estimated duration: XX days</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"109a365","css":".pc109a365{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 24px !important;}.pc109a365__overlay{padding:0px 0px 0px 0px !important;}.pc109a365 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc109a365{margin:4px 0 0 24px !important;}}@media screen and (max-width: 767px){.pc109a365{margin:4px 0 0 18px !important;}}","content":"After learning and analyzing best practices and the strategy, I will provide a project plan for website pages as per the design request. Wireframes will give a low-fidelity visual representation of the structure, hierarchy,","fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"4px","right":"0px","bottom":"0px","left":"24px"},"marginTablet":{"top":"4px","left":"24px"},"marginMobile":{"top":"4px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc109a365" data-block-id="109a365"><div class="pc109a365__overlay"><p class="pc-paragraph">After learning and analyzing best practices and the strategy, I will provide a project plan for website pages as per the design request. Wireframes will give a low-fidelity visual representation of the structure, hierarchy,</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"bdc435f","css":".pcbdc435f{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pcbdc435f__overlay{padding:0px 0px 0px 0px !important;}.pcbdc435f .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 1023px){.pcbdc435f{margin:16px 0 0 0 !important;}}@media screen and (max-width: 767px){.pcbdc435f{margin:13px 0 0 0 !important;}}","content":"Phase 4. Delivery","fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"marginTablet":{"top":"16px"},"marginMobile":{"top":"13px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcbdc435f" data-block-id="bdc435f"><div class="pcbdc435f__overlay"><p class="pc-paragraph">Phase 4. Delivery</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"88554a9","css":".pc88554a9{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 0px !important;}.pc88554a9__overlay{padding:0px 0px 0px 0px !important;}.pc88554a9 .pc-paragraph{text-align:left;color:#818181;font-size:14px;font-family:Readex Pro;font-weight:300;}","content":"Estimated duration: XX days","fontWeight":"300","fontFamily":"Readex Pro","color":"#818181","margin":{"top":"4px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc88554a9" data-block-id="88554a9"><div class="pc88554a9__overlay"><p class="pc-paragraph">Estimated duration: XX days</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"0bcee1f","css":".pc0bcee1f{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:4px 0px 0px 24px !important;}.pc0bcee1f__overlay{padding:0px 0px 0px 0px !important;}.pc0bcee1f .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 1023px){.pc0bcee1f{margin:4px 0 0 24px !important;}}@media screen and (max-width: 767px){.pc0bcee1f{margin:4px 0 0 18px !important;}}","content":"Once we've validated a concept, I'll start taking care of the design handoff that will be used by the developer in building the website. I'll need to collaborate with engineers to make sure the design is feasible to build.","fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"4px","right":"0px","bottom":"0px","left":"24px"},"marginTablet":{"top":"4px","left":"24px"},"marginMobile":{"top":"4px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc0bcee1f" data-block-id="0bcee1f"><div class="pc0bcee1f__overlay"><p class="pc-paragraph">Once we've validated a concept, I'll start taking care of the design handoff that will be used by the developer in building the website. I'll need to collaborate with engineers to make sure the design is feasible to build.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:asphalt-proposal-manager/heading {"uniqueId":"67f2620","css":".pc67f2620{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:40px 0px 22px 0px !important;}.pc67f2620__overlay{padding:0px 0px 0px 0px !important;}.pc67f2620 .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pc67f2620{margin:30px 0 20px 0 !important;}.pc67f2620 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc67f2620{margin:30px 0 18px 0 !important;}.pc67f2620 .pc-heading{font-size:20px;}}","content":"Terms of service","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","margin":{"top":"40px","right":"0px","bottom":"22px","left":"0px"},"marginTablet":{"top":"30px","bottom":"20px"},"marginMobile":{"top":"30px","bottom":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc67f2620" data-block-id="67f2620"><div class="pc67f2620__overlay"><h2 class="pc-heading">Terms of service</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"43d6ed7","css":".pc43d6ed7{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pc43d6ed7__overlay{padding:0px 0px 0px 0px !important;}.pc43d6ed7 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 767px){.pc43d6ed7 .pc-paragraph{font-size:14px;}}","content":"Confidentiality","fontSizeMobile":14,"fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc43d6ed7" data-block-id="43d6ed7"><div class="pc43d6ed7__overlay"><p class="pc-paragraph">Confidentiality</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"43fdddd","css":".pc43fdddd{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:8px 0px 0px 24px !important;}.pc43fdddd__overlay{padding:0px 0px 0px 0px !important;}.pc43fdddd .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc43fdddd .pc-paragraph{font-size:14px;}}","content":"In case of need, the project manager will sign an additional NDA contract and will not be allowed to share any confidential information about the project with anyone without the Client’s approval. Confidential information does not include information that: - the project manager knew before the Client disclosed it; - is or becomes public knowledge through no fault of the project manager; - the project manager obtains from sources other than the Client.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"8px","right":"0px","bottom":"0px","left":"24px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc43fdddd" data-block-id="43fdddd"><div class="pc43fdddd__overlay"><p class="pc-paragraph">In case of need, the project manager will sign an additional NDA contract and will not be allowed to share any confidential information about the project with anyone without the Client’s approval. Confidential information does not include information that: - the project manager knew before the Client disclosed it; - is or becomes public knowledge through no fault of the project manager; - the project manager obtains from sources other than the Client.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"e102a84","css":".pce102a84{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pce102a84__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pce102a84__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pce102a84__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pce102a84" data-block-id="e102a84"><div class="pce102a84__overlay"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"b81376f","css":".pcb81376f{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcb81376f__overlay{padding:0px 0px 0px 0px !important;}.pcb81376f .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 767px){.pcb81376f .pc-paragraph{font-size:14px;}}","content":"Ownership","fontSizeMobile":14,"fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcb81376f" data-block-id="b81376f"><div class="pcb81376f__overlay"><p class="pc-paragraph">Ownership</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"9714374","css":".pc9714374{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:8px 0px 0px 24px !important;}.pc9714374__overlay{padding:0px 0px 0px 0px !important;}.pc9714374 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc9714374 .pc-paragraph{font-size:14px;}}","content":"After the project is completed and the total amount for the project is paid in full, the client receives rights to all the designs produced. The Client guarantees that they have legal rights to all elements of text, photographs, and anything else that they provide the Designer with, and will not hold the Designer responsible for any third-party claims. The project manager will guarantee that they have legal rights to all elements related to the services they are providing and will not hold the Client responsible for any third-party claims.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"8px","right":"0px","bottom":"0px","left":"24px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc9714374" data-block-id="9714374"><div class="pc9714374__overlay"><p class="pc-paragraph">After the project is completed and the total amount for the project is paid in full, the client receives rights to all the designs produced. The Client guarantees that they have legal rights to all elements of text, photographs, and anything else that they provide the Designer with, and will not hold the Designer responsible for any third-party claims. The project manager will guarantee that they have legal rights to all elements related to the services they are providing and will not hold the Client responsible for any third-party claims.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"1be7810","css":".pc1be7810{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pc1be7810__overlay{padding:0px 0px 0px 0px !important;}.pc1be7810 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 767px){.pc1be7810 .pc-paragraph{font-size:14px;}}","content":"Out-of-Scope Requirements","fontSizeMobile":14,"fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc1be7810" data-block-id="1be7810"><div class="pc1be7810__overlay"><p class="pc-paragraph">Out-of-Scope Requirements</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"4cd54d5","css":".pc4cd54d5{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:8px 0px 0px 24px !important;}.pc4cd54d5__overlay{padding:0px 0px 0px 0px !important;}.pc4cd54d5 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pc4cd54d5 .pc-paragraph{font-size:14px;}}","content":"The project manager is not responsible for professional branding, copywriting, and illustration services. If in the process any of those appear needed, we’ll need to find extra relevant people to cooperate with.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"8px","right":"0px","bottom":"0px","left":"24px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc4cd54d5" data-block-id="4cd54d5"><div class="pc4cd54d5__overlay"><p class="pc-paragraph">The project manager is not responsible for professional branding, copywriting, and illustration services. If in the process any of those appear needed, we’ll need to find extra relevant people to cooperate with.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"f3f0f95","css":".pcf3f0f95{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pcf3f0f95__overlay{padding:0px 0px 0px 0px !important;}.pcf3f0f95 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 767px){.pcf3f0f95 .pc-paragraph{font-size:14px;}}","content":"Breach of Agreement","fontSizeMobile":14,"fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcf3f0f95" data-block-id="f3f0f95"><div class="pcf3f0f95__overlay"><p class="pc-paragraph">Breach of Agreement</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"ce5cd68","css":".pcce5cd68{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:8px 0px 0px 24px !important;}.pcce5cd68__overlay{padding:0px 0px 0px 0px !important;}.pcce5cd68 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcce5cd68 .pc-paragraph{font-size:14px;}}","content":"Once the project is completed, the Client must pay the remainder of the cost. Failure to pay the remaining means that the Designer will retain the rights to all the designs produced along the project and will be able to break the confidentiality contract. If the client rejects the designs, the client is not allowed to use any designs produced. Should there be a desire to terminate the agreement before the completion of the project, the Client will notify the Designer 5 days in advance, and pay for services already completed and for hours already worked.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"8px","right":"0px","bottom":"0px","left":"24px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcce5cd68" data-block-id="ce5cd68"><div class="pcce5cd68__overlay"><p class="pc-paragraph">Once the project is completed, the Client must pay the remainder of the cost. Failure to pay the remaining means that the Designer will retain the rights to all the designs produced along the project and will be able to break the confidentiality contract. If the client rejects the designs, the client is not allowed to use any designs produced. Should there be a desire to terminate the agreement before the completion of the project, the Client will notify the Designer 5 days in advance, and pay for services already completed and for hours already worked.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"6b62b06","css":".pc6b62b06{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:16px 0px 0px 0px !important;}.pc6b62b06__overlay{padding:0px 0px 0px 0px !important;}.pc6b62b06 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;}@media screen and (max-width: 767px){.pc6b62b06 .pc-paragraph{font-size:14px;}}","content":"Additional Scope","fontSizeMobile":14,"fontFamily":"Readex Pro","margin":{"top":"16px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pc6b62b06" data-block-id="6b62b06"><div class="pc6b62b06__overlay"><p class="pc-paragraph">Additional Scope</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"f695d33","css":".pcf695d33{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:8px 0px 0px 24px !important;}.pcf695d33__overlay{padding:0px 0px 0px 0px !important;}.pcf695d33 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcf695d33 .pc-paragraph{font-size:14px;}}","content":"Any additions to the scope of the project can be denied by a service provider. If the client still wants to add extra scope, the Client must send the details needed to initiate an additional project. At that point, the Designer will provide another invoice with the cost for the additional deliverables. Anything that is not covered under the deliverable items is considered outside the scope.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro","margin":{"top":"8px","right":"0px","bottom":"0px","left":"24px"}} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcf695d33" data-block-id="f695d33"><div class="pcf695d33__overlay"><p class="pc-paragraph">Any additions to the scope of the project can be denied by a service provider. If the client still wants to add extra scope, the Client must send the details needed to initiate an additional project. At that point, the Designer will provide another invoice with the cost for the additional deliverables. Anything that is not covered under the deliverable items is considered outside the scope.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"c03481e","css":".pcc03481e{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pcc03481e__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pcc03481e__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pcc03481e__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pcc03481e" data-block-id="c03481e"><div class="pcc03481e__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"34bcc41","css":".pc34bcc41{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 24px 0px !important;}.pc34bcc41__overlay{padding:0px 0px 0px 0px !important;}.pc34bcc41 .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pc34bcc41{margin:0px 0 22px 0 !important;}.pc34bcc41 .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc34bcc41{margin:0px 0 20px 0 !important;}.pc34bcc41 .pc-heading{font-size:20px;}}","content":"Project Billing","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"24px","left":"0px"},"marginTablet":{"top":"0px","bottom":"22px"},"marginMobile":{"top":"0px","bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc34bcc41" data-block-id="34bcc41"><div class="pc34bcc41__overlay"><h2 class="pc-heading">Project Billing</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"d1d873f","css":".pcd1d873f{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcd1d873f__overlay{padding:0px 0px 0px 0px !important;}.pcd1d873f .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcd1d873f .pc-paragraph{font-size:14px;}}","content":"If you are unhappy about the progress of the project, feel we are not finding an appropriate angle, and/or feel that you voice and input is not being acknowledged, kindly discuss this with me. I would encourage that we schedule a call rather than e-mail ; I am very easy going and even easier to talk to.","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcd1d873f" data-block-id="d1d873f"><div class="pcd1d873f__overlay"><p class="pc-paragraph">If you are unhappy about the progress of the project, feel we are not finding an appropriate angle, and/or feel that you voice and input is not being acknowledged, kindly discuss this with me. I would encourage that we schedule a call rather than e-mail ; I am very easy going and even easier to talk to.</p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"748c391","css":".pc748c391{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:50px 0px 0px 0px !important;max-width:1024px;}.pc748c391__overlay{padding:0px 0px 0px 0px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"50px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pc748c391" data-block-id="748c391"><div class="pc748c391__overlay"><!-- wp:asphalt-proposal-manager/pricing {"uniqueId":"b86da5b","css":".pcb86da5b{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcb86da5b__overlay{padding:0px 0px 0px 0px !important;}.pcb86da5b table thead th{background-color:#ffffff;color:#000000;font-weight:500;padding:8px 14px 8px 14px;font-family:Readex Pro;font-size:14px;}.pcb86da5b table tbody{background-color:#ffffff;}.pcb86da5b table tbody tr td{border-bottom-color:#E1E1E1;padding:15px 15px 15px 15px;}.pcb86da5b table tbody tr td .pc-pricing-item-title{color:#000000;font-family:Readex Pro;font-weight:400;font-size:16px;}.pcb86da5b table tbody tr td .pc-pricing-item-wrapper{margin:0px 0px 5px 0px;}.pcb86da5b table tbody tr td .pc-pricing-item-description{color:#000000;font-family:Readex Pro;font-weight:300;font-size:14px;}.pcb86da5b table tbody tr td.pc-pricing-column{color:#000000;font-family:Readex Pro;font-weight:300;font-size:16px;}.pcb86da5b table tfoot tr.pc-subtotal-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:9px 0 0 0;}.pcb86da5b table tfoot tr.pc-adjustments-row td{font-family:Readex Pro;font-weight:400;font-size:16px;padding:10px 0 0 0;}.pcb86da5b table tfoot tr.pc-total-row td{font-family:Readex Pro;font-weight:400;font-size:20px;padding:10px 0 0 0;}","tableTitle":"Project Billing","items":[{"title":"First Project Meeting","description":"Gather information about\u003cbr\u003ethe project","price":1245,"quantity":43,"isChecked":true},{"title":"Feedback from clients","description":"Implement client feedback","price":1245,"quantity":43,"isChecked":true},{"title":"Final project handover","description":"Transfer everything to client","price":1245,"quantity":43,"isChecked":false}],"showSubtotal":true,"showTotal":true,"headerFontWeight":"500","headerFontFamily":"Readex Pro","headerFontSize":14,"headerPadding":{"top":"8px","right":"14px","bottom":"8px","left":"14px"},"headerBackground":"#ffffff","headerColor":"#000000","bodyBackground":"#ffffff","titleColor":"#000000","titleFontFamily":"Readex Pro","titleFontWeight":"400","titleFontSize":16,"descriptionColor":"#000000","descriptionFontFamily":"Readex Pro","descriptionFontWeight":"300","descriptionFontSize":14,"pricingColor":"#000000","pricingFontFamily":"Readex Pro","pricingFontWeight":"300","pricingFontSize":16,"subtotalFontFamily":"Readex Pro","subtotalFontWeight":"400","subtotalFontSize":16,"subtotalMargin":{"top":"9px"},"adjustmentsFontFamily":"Readex Pro","adjustmentsFontWeight":"400","adjustmentsFontSize":16,"adjustmentsMargin":{"top":"10px"},"totalFontFamily":"Readex Pro","totalFontWeight":"400","totalFontSize":20,"totalMargin":{"top":"10px"},"background":{"type":"color","repeat":"no-repeat","size":"cover"},"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"b661a2a","css":".pcb661a2a{background:url(<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>);background-repeat:no-repeat;background-size:cover;background-position:top center;border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:600px;}.pcb661a2a__overlay{padding:100px 36px 70px 36px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}@media screen and (max-width: 1023px){.pcb661a2a__overlay{padding:80px 36px 50px 36px !important;}}@media screen and (max-width: 767px){.pcb661a2a__overlay{padding:50px 18px 50px 18px !important;}}","maxWidth":{"type":"custom","value":600},"background":{"type":"image","repeat":"no-repeat","size":"cover","value":"<?php echo esc_url( asphalt_proposal_manager_url('assets/templates/1/proposal-secondary-bg-cover.webp') ) ?>"},"padding":{"top":"100px","right":"36px","bottom":"70px","left":"36px"},"paddingTablet":{"top":"80px","right":"36px","bottom":"50px","left":"36px"},"paddingMobile":{"top":"50px","right":"18px","bottom":"50px","left":"18px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pcb661a2a" data-block-id="b661a2a"><div class="pcb661a2a__overlay"><!-- wp:asphalt-proposal-manager/heading {"uniqueId":"3e5cf4f","css":".pc3e5cf4f{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 24px 0px !important;}.pc3e5cf4f__overlay{padding:0px 0px 0px 0px !important;}.pc3e5cf4f .pc-heading{text-align:left;color:#000000;font-size:32px;font-family:Readex Pro;font-weight:500;}@media screen and (max-width: 1023px){.pc3e5cf4f{margin:0px 0 22px 0 !important;}.pc3e5cf4f .pc-heading{font-size:24px;}}@media screen and (max-width: 767px){.pc3e5cf4f{margin:0px 0 20px 0 !important;}.pc3e5cf4f .pc-heading{font-size:20px;}}","content":"Accept \u0026amp; Sign","fontSize":32,"fontSizeTablet":24,"fontSizeMobile":20,"fontWeight":"500","fontFamily":"Readex Pro","margin":{"top":"0px","right":"0px","bottom":"24px","left":"0px"},"marginTablet":{"top":"0px","bottom":"22px"},"marginMobile":{"top":"0px","bottom":"20px"}} -->
<div class="wp-block-asphalt-proposal-manager-heading pc3e5cf4f" data-block-id="3e5cf4f"><div class="pc3e5cf4f__overlay"><h2 class="pc-heading">Accept &amp; Sign</h2></div></div>
<!-- /wp:asphalt-proposal-manager/heading -->

<!-- wp:asphalt-proposal-manager/paragraph {"uniqueId":"bc60897","css":".pcbc60897{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;}.pcbc60897__overlay{padding:0px 0px 0px 0px !important;}.pcbc60897 .pc-paragraph{text-align:left;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:300;}@media screen and (max-width: 767px){.pcbc60897 .pc-paragraph{font-size:14px;}}","content":"By signing this proposal you agree with the deliverables and terms of services. These terms are valid for only the said provision, and the remaining provisions (if there are any other) shall continue to be valid and enforceable.  ","fontSizeMobile":14,"fontWeight":"300","fontFamily":"Readex Pro"} -->
<div class="wp-block-asphalt-proposal-manager-paragraph pcbc60897" data-block-id="bc60897"><div class="pcbc60897__overlay"><p class="pc-paragraph">By signing this proposal you agree with the deliverables and terms of services. These terms are valid for only the said provision, and the remaining provisions (if there are any other) shall continue to be valid and enforceable.  </p></div></div>
<!-- /wp:asphalt-proposal-manager/paragraph -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"f5d2e3c","css":".pcf5d2e3c{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:40px 0px 0px 0px !important;max-width:1024px;}.pcf5d2e3c__overlay{padding:0px 0px 0px 0px !important;display:flex;flex-direction:row;align-items:center;justify-content:space-between;}","display":"flex","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"40px","right":"0px","bottom":"0px","left":"0px"}} -->
<div class="wp-block-asphalt-proposal-manager-container pcf5d2e3c" data-block-id="f5d2e3c"><div class="pcf5d2e3c__overlay"><!-- wp:asphalt-proposal-manager/container {"uniqueId":"f8d5398","css":".pcf8d5398{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pcf8d5398__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:row;align-items:center;justify-content:space-between;}","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pcf8d5398" data-block-id="f8d5398"><div class="pcf8d5398__overlay"><!-- wp:asphalt-proposal-manager/sender-name {"uniqueId":"f9d0551","css":".pcf9d0551{background:#ffeca8;border-style:solid;border-color:#e5dc11;border-width:1px 1px 1px 1px;margin:0px 0px 8px 0px !important;}.pcf9d0551__overlay{padding:7px 15px 7px 15px !important;}.pcf9d0551 .pc-sender-name{text-align:left;color:#000000;font-size:16px;font-weight:400;}","borderStyle":"solid","borderColor":"#e5dc11","borderWidth":{"top":"1px","right":"1px","bottom":"1px","left":"1px"},"content":"Sender name","background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffeca8"},"padding":{"top":"7px","right":"15px","bottom":"7px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"8px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/signature {"uniqueId":"017887b","signatureType":"upload","placeholder":"Client Signature","css":".pc017887b{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:16px;font-family:Readex Pro;font-weight:300;width:200px;}.pc017887b__overlay{padding:15px 10px 15px 15px !important;}.pc017887b .signature-content{text-align:left;}","fontWeight":"300","fontFamily":"Readex Pro","padding":{"top":"15px","right":"10px","bottom":"15px","left":"15px"},"className":"wp-block-asphalt-proposal-manager-signature pc017887b"} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container -->

<!-- wp:asphalt-proposal-manager/container {"uniqueId":"6150c79","css":".pc6150c79{border-style:none;border-color:#000000;border-width:0px 0px 0px 0px;margin:0px 0px 0px 0px !important;max-width:200px;}.pc6150c79__overlay{padding:5px 5px 5px 5px !important;display:block;flex-direction:column;align-items:flex-end;justify-content:flex-start;}","flexDirection":"column","alignItems":"flex-end","justifyContent":"flex-start","maxWidth":{"type":"custom","value":200}} -->
<div class="wp-block-asphalt-proposal-manager-container pc6150c79" data-block-id="6150c79"><div class="pc6150c79__overlay"><!-- wp:asphalt-proposal-manager/client-name {"uniqueId":"860543e","css":".pc860543e{background:#ffeca8;border-style:solid;border-color:#e5dc11;border-width:1px 1px 1px 1px;margin:0px 0px 8px 0px !important;}.pc860543e__overlay{padding:7px 15px 7px 15px !important;}.pc860543e .pc-client-name{text-align:left;color:#000000;font-size:14px;font-weight:400;}","borderStyle":"solid","borderColor":"#e5dc11","borderWidth":{"top":"1px","right":"1px","bottom":"1px","left":"1px"},"content":"Client name","background":{"type":"color","repeat":"no-repeat","size":"cover","value":"#ffeca8"},"padding":{"top":"7px","right":"15px","bottom":"7px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"8px","left":"0px"}} /-->

<!-- wp:asphalt-proposal-manager/signature {"uniqueId":"bcd8ed9","userType":"client","placeholder":"Signature","css":".pcbcd8ed9{background:#FFECA8;border-style:solid;border-color:#E5DC11;border-width:1px 1px 1px 1px;margin:0px 0px 0px 0px !important;color:#000000;font-size:14px;font-family:Readex Pro;font-weight:400;width:200px;}.pcbcd8ed9__overlay{padding:16px 10px 16px 10px !important;}.pcbcd8ed9 .signature-content{text-align:center;}","fontSize":14,"fontFamily":"Readex Pro","padding":{"top":"16px","right":"10px","bottom":"16px","left":"10px"},"alignment":"center"} /--></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container --></div></div>
<!-- /wp:asphalt-proposal-manager/container -->